// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: oneof/oneof.proto

package oneof

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OneOfService_OneOf_FullMethodName = "/oneof.OneOfService/OneOf"
)

// OneOfServiceClient is the client API for OneOfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OneOfServiceClient interface {
	OneOf(ctx context.Context, in *OneOfRequest, opts ...grpc.CallOption) (*OneOfResponse, error)
}

type oneOfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOneOfServiceClient(cc grpc.ClientConnInterface) OneOfServiceClient {
	return &oneOfServiceClient{cc}
}

func (c *oneOfServiceClient) OneOf(ctx context.Context, in *OneOfRequest, opts ...grpc.CallOption) (*OneOfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OneOfResponse)
	err := c.cc.Invoke(ctx, OneOfService_OneOf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OneOfServiceServer is the server API for OneOfService service.
// All implementations must embed UnimplementedOneOfServiceServer
// for forward compatibility.
type OneOfServiceServer interface {
	OneOf(context.Context, *OneOfRequest) (*OneOfResponse, error)
	mustEmbedUnimplementedOneOfServiceServer()
}

// UnimplementedOneOfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOneOfServiceServer struct{}

func (UnimplementedOneOfServiceServer) OneOf(context.Context, *OneOfRequest) (*OneOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OneOf not implemented")
}
func (UnimplementedOneOfServiceServer) mustEmbedUnimplementedOneOfServiceServer() {}
func (UnimplementedOneOfServiceServer) testEmbeddedByValue()                      {}

// UnsafeOneOfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OneOfServiceServer will
// result in compilation errors.
type UnsafeOneOfServiceServer interface {
	mustEmbedUnimplementedOneOfServiceServer()
}

func RegisterOneOfServiceServer(s grpc.ServiceRegistrar, srv OneOfServiceServer) {
	// If the following call pancis, it indicates UnimplementedOneOfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OneOfService_ServiceDesc, srv)
}

func _OneOfService_OneOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneOfServiceServer).OneOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OneOfService_OneOf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneOfServiceServer).OneOf(ctx, req.(*OneOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OneOfService_ServiceDesc is the grpc.ServiceDesc for OneOfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OneOfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oneof.OneOfService",
	HandlerType: (*OneOfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OneOf",
			Handler:    _OneOfService_OneOf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oneof/oneof.proto",
}
