// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: nosvc/nosvc.proto

package nosvc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type No struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            string                 `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *No) Reset() {
	*x = No{}
	mi := &file_nosvc_nosvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *No) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*No) ProtoMessage() {}

func (x *No) ProtoReflect() protoreflect.Message {
	mi := &file_nosvc_nosvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use No.ProtoReflect.Descriptor instead.
func (*No) Descriptor() ([]byte, []int) {
	return file_nosvc_nosvc_proto_rawDescGZIP(), []int{0}
}

func (x *No) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

type Svc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svc           string                 `protobuf:"bytes,1,opt,name=svc,proto3" json:"svc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Svc) Reset() {
	*x = Svc{}
	mi := &file_nosvc_nosvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Svc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Svc) ProtoMessage() {}

func (x *Svc) ProtoReflect() protoreflect.Message {
	mi := &file_nosvc_nosvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Svc.ProtoReflect.Descriptor instead.
func (*Svc) Descriptor() ([]byte, []int) {
	return file_nosvc_nosvc_proto_rawDescGZIP(), []int{1}
}

func (x *Svc) GetSvc() string {
	if x != nil {
		return x.Svc
	}
	return ""
}

var File_nosvc_nosvc_proto protoreflect.FileDescriptor

const file_nosvc_nosvc_proto_rawDesc = "" +
	"\n" +
	"\x11nosvc/nosvc.proto\x12\x05nosvc\"\x14\n" +
	"\x02No\x12\x0e\n" +
	"\x02no\x18\x01 \x01(\tR\x02no\"\x17\n" +
	"\x03Svc\x12\x10\n" +
	"\x03svc\x18\x01 \x01(\tR\x03svcB\tZ\a.;nosvcb\x06proto3"

var (
	file_nosvc_nosvc_proto_rawDescOnce sync.Once
	file_nosvc_nosvc_proto_rawDescData []byte
)

func file_nosvc_nosvc_proto_rawDescGZIP() []byte {
	file_nosvc_nosvc_proto_rawDescOnce.Do(func() {
		file_nosvc_nosvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nosvc_nosvc_proto_rawDesc), len(file_nosvc_nosvc_proto_rawDesc)))
	})
	return file_nosvc_nosvc_proto_rawDescData
}

var file_nosvc_nosvc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nosvc_nosvc_proto_goTypes = []any{
	(*No)(nil),  // 0: nosvc.No
	(*Svc)(nil), // 1: nosvc.Svc
}
var file_nosvc_nosvc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nosvc_nosvc_proto_init() }
func file_nosvc_nosvc_proto_init() {
	if File_nosvc_nosvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nosvc_nosvc_proto_rawDesc), len(file_nosvc_nosvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nosvc_nosvc_proto_goTypes,
		DependencyIndexes: file_nosvc_nosvc_proto_depIdxs,
		MessageInfos:      file_nosvc_nosvc_proto_msgTypes,
	}.Build()
	File_nosvc_nosvc_proto = out.File
	file_nosvc_nosvc_proto_goTypes = nil
	file_nosvc_nosvc_proto_depIdxs = nil
}
