// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: oneof/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Types that are assignable to Value:
	//
	//	*PaginationRequest_PageToken
	//	*PaginationRequest_PageOffset
	Value isPaginationRequest_Value `protobuf_oneof:"value"`
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneof_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_oneof_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (m *PaginationRequest) GetValue() isPaginationRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *PaginationRequest) GetPageToken() string {
	if x, ok := x.GetValue().(*PaginationRequest_PageToken); ok {
		return x.PageToken
	}
	return ""
}

func (x *PaginationRequest) GetPageOffset() int32 {
	if x, ok := x.GetValue().(*PaginationRequest_PageOffset); ok {
		return x.PageOffset
	}
	return 0
}

type isPaginationRequest_Value interface {
	isPaginationRequest_Value()
}

type PaginationRequest_PageToken struct {
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof"`
}

type PaginationRequest_PageOffset struct {
	PageOffset int32 `protobuf:"varint,3,opt,name=page_offset,json=pageOffset,proto3,oneof"`
}

func (*PaginationRequest_PageToken) isPaginationRequest_Value() {}

func (*PaginationRequest_PageOffset) isPaginationRequest_Value() {}

var File_oneof_common_common_proto protoreflect.FileDescriptor

var file_oneof_common_common_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x22, 0x7d, 0x0a, 0x11, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4e, 0x61, 0x74, 0x68, 0x61, 0x6e, 0x42, 0x61, 0x75, 0x6c, 0x63, 0x68, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x63, 0x6f, 0x62, 0x72, 0x61, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneof_common_common_proto_rawDescOnce sync.Once
	file_oneof_common_common_proto_rawDescData = file_oneof_common_common_proto_rawDesc
)

func file_oneof_common_common_proto_rawDescGZIP() []byte {
	file_oneof_common_common_proto_rawDescOnce.Do(func() {
		file_oneof_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneof_common_common_proto_rawDescData)
	})
	return file_oneof_common_common_proto_rawDescData
}

var file_oneof_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_oneof_common_common_proto_goTypes = []interface{}{
	(*PaginationRequest)(nil), // 0: common.PaginationRequest
}
var file_oneof_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oneof_common_common_proto_init() }
func file_oneof_common_common_proto_init() {
	if File_oneof_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneof_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oneof_common_common_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PaginationRequest_PageToken)(nil),
		(*PaginationRequest_PageOffset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneof_common_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneof_common_common_proto_goTypes,
		DependencyIndexes: file_oneof_common_common_proto_depIdxs,
		MessageInfos:      file_oneof_common_common_proto_msgTypes,
	}.Build()
	File_oneof_common_common_proto = out.File
	file_oneof_common_common_proto_rawDesc = nil
	file_oneof_common_common_proto_goTypes = nil
	file_oneof_common_common_proto_depIdxs = nil
}
