// Code generated by protoc-gen-cobra. DO NOT EDIT.

package pb

import (
	client "github.com/NathanBaulch/protoc-gen-cobra/client"
	iocodec "github.com/NathanBaulch/protoc-gen-cobra/iocodec"
	proto "github.com/golang/protobuf/proto"
	cobra "github.com/spf13/cobra"
	grpc "google.golang.org/grpc"
	io "io"
)

func CacheClientCommand(cfgs ...*client.Config) *cobra.Command {
	cfg := client.DefaultConfig
	if len(cfgs) > 0 {
		cfg = cfgs[0]
	}
	cmd := &cobra.Command{
		Use:   "cache",
		Short: "Cache service client",
		Long:  "",
	}
	cfg.BindFlags(cmd.PersistentFlags())
	d := &client.Dialer{Config: cfg}
	cmd.AddCommand(
		_CacheSetCommand(d),
		_CacheGetCommand(d),
		_CacheMultiSetCommand(d),
		_CacheMultiGetCommand(d),
	)
	return cmd
}

func _CacheSetCommand(d *client.Dialer) *cobra.Command {
	req := &SetRequest{}

	cmd := &cobra.Command{
		Use:   "set",
		Short: "Set RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			return d.RoundTrip(cmd.Context(), func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewCacheClient(cc)
				v := &SetRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.Set(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.Key, "key", "", "")
	cmd.PersistentFlags().StringVar(&req.Value, "value", "", "")

	return cmd
}

func _CacheGetCommand(d *client.Dialer) *cobra.Command {
	req := &GetRequest{}

	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			return d.RoundTrip(cmd.Context(), func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewCacheClient(cc)
				v := &GetRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.Get(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.Key, "key", "", "")

	return cmd
}

func _CacheMultiSetCommand(d *client.Dialer) *cobra.Command {
	req := &SetRequest{}

	cmd := &cobra.Command{
		Use:   "multiset",
		Short: "MultiSet RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			return d.RoundTrip(cmd.Context(), func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewCacheClient(cc)
				v := &SetRequest{}

				stm, err := cli.MultiSet(cmd.Context())
				if err != nil {
					return err
				}
				for {
					if err := in(v); err != nil {
						if err == io.EOF {
							_ = stm.CloseSend()
							break
						}
						return err
					}
					proto.Merge(v, req)
					if err = stm.Send(v); err != nil {
						return err
					}
				}

				res, err := stm.CloseAndRecv()
				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.Key, "key", "", "")
	cmd.PersistentFlags().StringVar(&req.Value, "value", "", "")

	return cmd
}

func _CacheMultiGetCommand(d *client.Dialer) *cobra.Command {
	req := &GetRequest{}

	cmd := &cobra.Command{
		Use:   "multiget",
		Short: "MultiGet RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			return d.RoundTrip(cmd.Context(), func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewCacheClient(cc)
				v := &GetRequest{}

				stm, err := cli.MultiGet(cmd.Context())
				if err != nil {
					return err
				}
				for {
					if err := in(v); err != nil {
						if err == io.EOF {
							_ = stm.CloseSend()
							break
						}
						return err
					}
					proto.Merge(v, req)
					if err = stm.Send(v); err != nil {
						return err
					}
				}

				for {
					res, err := stm.Recv()
					if err != nil {
						if err == io.EOF {
							break
						}
						return err
					}
					if err = out(res); err != nil {
						return err
					}
				}
				return nil

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.Key, "key", "", "")

	return cmd
}
