// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: crud.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CRUDObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDObject) Reset() {
	*x = CRUDObject{}
	mi := &file_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDObject) ProtoMessage() {}

func (x *CRUDObject) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDObject.ProtoReflect.Descriptor instead.
func (*CRUDObject) Descriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{0}
}

func (x *CRUDObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CRUDObject) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type CreateCRUD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCRUD) Reset() {
	*x = CreateCRUD{}
	mi := &file_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCRUD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCRUD) ProtoMessage() {}

func (x *CreateCRUD) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCRUD.ProtoReflect.Descriptor instead.
func (*CreateCRUD) Descriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCRUD) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCRUD) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type GetCRUD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRUD) Reset() {
	*x = GetCRUD{}
	mi := &file_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRUD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRUD) ProtoMessage() {}

func (x *GetCRUD) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRUD.ProtoReflect.Descriptor instead.
func (*GetCRUD) Descriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{2}
}

func (x *GetCRUD) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_crud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{3}
}

var File_crud_proto protoreflect.FileDescriptor

const file_crud_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"crud.proto\x12\aexample\"E\n" +
	"\n" +
	"CRUDObject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"E\n" +
	"\n" +
	"CreateCRUD\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\x1d\n" +
	"\aGetCRUD\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\a\n" +
	"\x05Empty2\xcb\x01\n" +
	"\x04CRUD\x122\n" +
	"\x06Create\x12\x13.example.CreateCRUD\x1a\x13.example.CRUDObject\x12,\n" +
	"\x03Get\x12\x10.example.GetCRUD\x1a\x13.example.CRUDObject\x122\n" +
	"\x06Update\x12\x13.example.CRUDObject\x1a\x13.example.CRUDObject\x12-\n" +
	"\x06Delete\x12\x13.example.CRUDObject\x1a\x0e.example.EmptyB\x06Z\x04.;pbb\x06proto3"

var (
	file_crud_proto_rawDescOnce sync.Once
	file_crud_proto_rawDescData []byte
)

func file_crud_proto_rawDescGZIP() []byte {
	file_crud_proto_rawDescOnce.Do(func() {
		file_crud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crud_proto_rawDesc), len(file_crud_proto_rawDesc)))
	})
	return file_crud_proto_rawDescData
}

var file_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_crud_proto_goTypes = []any{
	(*CRUDObject)(nil), // 0: example.CRUDObject
	(*CreateCRUD)(nil), // 1: example.CreateCRUD
	(*GetCRUD)(nil),    // 2: example.GetCRUD
	(*Empty)(nil),      // 3: example.Empty
}
var file_crud_proto_depIdxs = []int32{
	1, // 0: example.CRUD.Create:input_type -> example.CreateCRUD
	2, // 1: example.CRUD.Get:input_type -> example.GetCRUD
	0, // 2: example.CRUD.Update:input_type -> example.CRUDObject
	0, // 3: example.CRUD.Delete:input_type -> example.CRUDObject
	0, // 4: example.CRUD.Create:output_type -> example.CRUDObject
	0, // 5: example.CRUD.Get:output_type -> example.CRUDObject
	0, // 6: example.CRUD.Update:output_type -> example.CRUDObject
	3, // 7: example.CRUD.Delete:output_type -> example.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crud_proto_init() }
func file_crud_proto_init() {
	if File_crud_proto != nil {
		return
	}
	file_crud_proto_msgTypes[0].OneofWrappers = []any{}
	file_crud_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crud_proto_rawDesc), len(file_crud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crud_proto_goTypes,
		DependencyIndexes: file_crud_proto_depIdxs,
		MessageInfos:      file_crud_proto_msgTypes,
	}.Build()
	File_crud_proto = out.File
	file_crud_proto_goTypes = nil
	file_crud_proto_depIdxs = nil
}
