// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.0
// source: cyclical.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bar1  *Bar   `protobuf:"bytes,1,opt,name=bar1,proto3" json:"bar1,omitempty"`
	Bar2  *Bar   `protobuf:"bytes,2,opt,name=bar2,proto3" json:"bar2,omitempty"`
	Foo   *Foo   `protobuf:"bytes,3,opt,name=foo,proto3" json:"foo,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyclical_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_cyclical_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_cyclical_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetBar1() *Bar {
	if x != nil {
		return x.Bar1
	}
	return nil
}

func (x *Foo) GetBar2() *Bar {
	if x != nil {
		return x.Bar2
	}
	return nil
}

func (x *Foo) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

func (x *Foo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo1  *Foo   `protobuf:"bytes,1,opt,name=foo1,proto3" json:"foo1,omitempty"`
	Foo2  *Foo   `protobuf:"bytes,2,opt,name=foo2,proto3" json:"foo2,omitempty"`
	Bar   *Bar   `protobuf:"bytes,3,opt,name=bar,proto3" json:"bar,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyclical_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_cyclical_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_cyclical_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetFoo1() *Foo {
	if x != nil {
		return x.Foo1
	}
	return nil
}

func (x *Bar) GetFoo2() *Foo {
	if x != nil {
		return x.Foo2
	}
	return nil
}

func (x *Bar) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

func (x *Bar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_cyclical_proto protoreflect.FileDescriptor

var file_cyclical_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x79, 0x63, 0x6c, 0x69, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x7f, 0x0a, 0x03, 0x46, 0x6f, 0x6f,
	0x12, 0x20, 0x0a, 0x04, 0x62, 0x61, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x04, 0x62, 0x61,
	0x72, 0x31, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x61, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x04,
	0x62, 0x61, 0x72, 0x32, 0x12, 0x1e, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x52,
	0x03, 0x66, 0x6f, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7f, 0x0a, 0x03, 0x42, 0x61,
	0x72, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x52, 0x04, 0x66,
	0x6f, 0x6f, 0x31, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x52,
	0x04, 0x66, 0x6f, 0x6f, 0x32, 0x12, 0x1e, 0x0a, 0x03, 0x62, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x72,
	0x52, 0x03, 0x62, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x2e, 0x0a, 0x08, 0x43,
	0x79, 0x63, 0x6c, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12,
	0x0c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x1a, 0x0c, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cyclical_proto_rawDescOnce sync.Once
	file_cyclical_proto_rawDescData = file_cyclical_proto_rawDesc
)

func file_cyclical_proto_rawDescGZIP() []byte {
	file_cyclical_proto_rawDescOnce.Do(func() {
		file_cyclical_proto_rawDescData = protoimpl.X.CompressGZIP(file_cyclical_proto_rawDescData)
	})
	return file_cyclical_proto_rawDescData
}

var file_cyclical_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cyclical_proto_goTypes = []interface{}{
	(*Foo)(nil), // 0: example.Foo
	(*Bar)(nil), // 1: example.Bar
}
var file_cyclical_proto_depIdxs = []int32{
	1, // 0: example.Foo.bar1:type_name -> example.Bar
	1, // 1: example.Foo.bar2:type_name -> example.Bar
	0, // 2: example.Foo.foo:type_name -> example.Foo
	0, // 3: example.Bar.foo1:type_name -> example.Foo
	0, // 4: example.Bar.foo2:type_name -> example.Foo
	1, // 5: example.Bar.bar:type_name -> example.Bar
	0, // 6: example.Cyclical.Test:input_type -> example.Foo
	1, // 7: example.Cyclical.Test:output_type -> example.Bar
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cyclical_proto_init() }
func file_cyclical_proto_init() {
	if File_cyclical_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cyclical_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyclical_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cyclical_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cyclical_proto_goTypes,
		DependencyIndexes: file_cyclical_proto_depIdxs,
		MessageInfos:      file_cyclical_proto_msgTypes,
	}.Build()
	File_cyclical_proto = out.File
	file_cyclical_proto_rawDesc = nil
	file_cyclical_proto_goTypes = nil
	file_cyclical_proto_depIdxs = nil
}
