// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: cyclical.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bar1          *Bar                   `protobuf:"bytes,1,opt,name=bar1,proto3" json:"bar1,omitempty"`
	Bar2          *Bar                   `protobuf:"bytes,2,opt,name=bar2,proto3" json:"bar2,omitempty"`
	Foo           *Foo                   `protobuf:"bytes,3,opt,name=foo,proto3" json:"foo,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_cyclical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_cyclical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_cyclical_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetBar1() *Bar {
	if x != nil {
		return x.Bar1
	}
	return nil
}

func (x *Foo) GetBar2() *Bar {
	if x != nil {
		return x.Bar2
	}
	return nil
}

func (x *Foo) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

func (x *Foo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo1          *Foo                   `protobuf:"bytes,1,opt,name=foo1,proto3" json:"foo1,omitempty"`
	Foo2          *Foo                   `protobuf:"bytes,2,opt,name=foo2,proto3" json:"foo2,omitempty"`
	Bar           *Bar                   `protobuf:"bytes,3,opt,name=bar,proto3" json:"bar,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_cyclical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_cyclical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_cyclical_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetFoo1() *Foo {
	if x != nil {
		return x.Foo1
	}
	return nil
}

func (x *Bar) GetFoo2() *Foo {
	if x != nil {
		return x.Foo2
	}
	return nil
}

func (x *Bar) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

func (x *Bar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_cyclical_proto protoreflect.FileDescriptor

const file_cyclical_proto_rawDesc = "" +
	"\n" +
	"\x0ecyclical.proto\x12\aexample\"\x7f\n" +
	"\x03Foo\x12 \n" +
	"\x04bar1\x18\x01 \x01(\v2\f.example.BarR\x04bar1\x12 \n" +
	"\x04bar2\x18\x02 \x01(\v2\f.example.BarR\x04bar2\x12\x1e\n" +
	"\x03foo\x18\x03 \x01(\v2\f.example.FooR\x03foo\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x7f\n" +
	"\x03Bar\x12 \n" +
	"\x04foo1\x18\x01 \x01(\v2\f.example.FooR\x04foo1\x12 \n" +
	"\x04foo2\x18\x02 \x01(\v2\f.example.FooR\x04foo2\x12\x1e\n" +
	"\x03bar\x18\x03 \x01(\v2\f.example.BarR\x03bar\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value2.\n" +
	"\bCyclical\x12\"\n" +
	"\x04Test\x12\f.example.Foo\x1a\f.example.BarB\x06Z\x04.;pbb\x06proto3"

var (
	file_cyclical_proto_rawDescOnce sync.Once
	file_cyclical_proto_rawDescData []byte
)

func file_cyclical_proto_rawDescGZIP() []byte {
	file_cyclical_proto_rawDescOnce.Do(func() {
		file_cyclical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cyclical_proto_rawDesc), len(file_cyclical_proto_rawDesc)))
	})
	return file_cyclical_proto_rawDescData
}

var file_cyclical_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cyclical_proto_goTypes = []any{
	(*Foo)(nil), // 0: example.Foo
	(*Bar)(nil), // 1: example.Bar
}
var file_cyclical_proto_depIdxs = []int32{
	1, // 0: example.Foo.bar1:type_name -> example.Bar
	1, // 1: example.Foo.bar2:type_name -> example.Bar
	0, // 2: example.Foo.foo:type_name -> example.Foo
	0, // 3: example.Bar.foo1:type_name -> example.Foo
	0, // 4: example.Bar.foo2:type_name -> example.Foo
	1, // 5: example.Bar.bar:type_name -> example.Bar
	0, // 6: example.Cyclical.Test:input_type -> example.Foo
	1, // 7: example.Cyclical.Test:output_type -> example.Bar
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cyclical_proto_init() }
func file_cyclical_proto_init() {
	if File_cyclical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cyclical_proto_rawDesc), len(file_cyclical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cyclical_proto_goTypes,
		DependencyIndexes: file_cyclical_proto_depIdxs,
		MessageInfos:      file_cyclical_proto_msgTypes,
	}.Build()
	File_cyclical_proto = out.File
	file_cyclical_proto_goTypes = nil
	file_cyclical_proto_depIdxs = nil
}
