// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: deprecated.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Deprecated_Obsolete_FullMethodName = "/example.Deprecated/Obsolete"
)

// DeprecatedClient is the client API for Deprecated service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Deprecated: Do not use.
type DeprecatedClient interface {
	// Deprecated: Do not use.
	Obsolete(ctx context.Context, in *ObsoleteRequest, opts ...grpc.CallOption) (*ObsoleteResponse, error)
}

type deprecatedClient struct {
	cc grpc.ClientConnInterface
}

// Deprecated: Do not use.
func NewDeprecatedClient(cc grpc.ClientConnInterface) DeprecatedClient {
	return &deprecatedClient{cc}
}

// Deprecated: Do not use.
func (c *deprecatedClient) Obsolete(ctx context.Context, in *ObsoleteRequest, opts ...grpc.CallOption) (*ObsoleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObsoleteResponse)
	err := c.cc.Invoke(ctx, Deprecated_Obsolete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeprecatedServer is the server API for Deprecated service.
// All implementations must embed UnimplementedDeprecatedServer
// for forward compatibility.
//
// Deprecated: Do not use.
type DeprecatedServer interface {
	// Deprecated: Do not use.
	Obsolete(context.Context, *ObsoleteRequest) (*ObsoleteResponse, error)
	mustEmbedUnimplementedDeprecatedServer()
}

// UnimplementedDeprecatedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeprecatedServer struct{}

func (UnimplementedDeprecatedServer) Obsolete(context.Context, *ObsoleteRequest) (*ObsoleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Obsolete not implemented")
}
func (UnimplementedDeprecatedServer) mustEmbedUnimplementedDeprecatedServer() {}
func (UnimplementedDeprecatedServer) testEmbeddedByValue()                    {}

// UnsafeDeprecatedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeprecatedServer will
// result in compilation errors.
type UnsafeDeprecatedServer interface {
	mustEmbedUnimplementedDeprecatedServer()
}

// Deprecated: Do not use.
func RegisterDeprecatedServer(s grpc.ServiceRegistrar, srv DeprecatedServer) {
	// If the following call pancis, it indicates UnimplementedDeprecatedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Deprecated_ServiceDesc, srv)
}

func _Deprecated_Obsolete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObsoleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeprecatedServer).Obsolete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deprecated_Obsolete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeprecatedServer).Obsolete(ctx, req.(*ObsoleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Deprecated_ServiceDesc is the grpc.ServiceDesc for Deprecated service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deprecated_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.Deprecated",
	HandlerType: (*DeprecatedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Obsolete",
			Handler:    _Deprecated_Obsolete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deprecated.proto",
}
