// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: deprecated.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObsoleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in deprecated.proto.
	Unused        string `protobuf:"bytes,1,opt,name=Unused,proto3" json:"Unused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObsoleteRequest) Reset() {
	*x = ObsoleteRequest{}
	mi := &file_deprecated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObsoleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsoleteRequest) ProtoMessage() {}

func (x *ObsoleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deprecated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsoleteRequest.ProtoReflect.Descriptor instead.
func (*ObsoleteRequest) Descriptor() ([]byte, []int) {
	return file_deprecated_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in deprecated.proto.
func (x *ObsoleteRequest) GetUnused() string {
	if x != nil {
		return x.Unused
	}
	return ""
}

type ObsoleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in deprecated.proto.
	Unused        string `protobuf:"bytes,1,opt,name=Unused,proto3" json:"Unused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObsoleteResponse) Reset() {
	*x = ObsoleteResponse{}
	mi := &file_deprecated_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObsoleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsoleteResponse) ProtoMessage() {}

func (x *ObsoleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deprecated_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsoleteResponse.ProtoReflect.Descriptor instead.
func (*ObsoleteResponse) Descriptor() ([]byte, []int) {
	return file_deprecated_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in deprecated.proto.
func (x *ObsoleteResponse) GetUnused() string {
	if x != nil {
		return x.Unused
	}
	return ""
}

var File_deprecated_proto protoreflect.FileDescriptor

const file_deprecated_proto_rawDesc = "" +
	"\n" +
	"\x10deprecated.proto\x12\aexample\"-\n" +
	"\x0fObsoleteRequest\x12\x1a\n" +
	"\x06Unused\x18\x01 \x01(\tB\x02\x18\x01R\x06Unused\".\n" +
	"\x10ObsoleteResponse\x12\x1a\n" +
	"\x06Unused\x18\x01 \x01(\tB\x02\x18\x01R\x06Unused2W\n" +
	"\n" +
	"Deprecated\x12D\n" +
	"\bObsolete\x12\x18.example.ObsoleteRequest\x1a\x19.example.ObsoleteResponse\"\x03\x88\x02\x01\x1a\x03\x88\x02\x01B\x06Z\x04.;pbb\x06proto3"

var (
	file_deprecated_proto_rawDescOnce sync.Once
	file_deprecated_proto_rawDescData []byte
)

func file_deprecated_proto_rawDescGZIP() []byte {
	file_deprecated_proto_rawDescOnce.Do(func() {
		file_deprecated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deprecated_proto_rawDesc), len(file_deprecated_proto_rawDesc)))
	})
	return file_deprecated_proto_rawDescData
}

var file_deprecated_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deprecated_proto_goTypes = []any{
	(*ObsoleteRequest)(nil),  // 0: example.ObsoleteRequest
	(*ObsoleteResponse)(nil), // 1: example.ObsoleteResponse
}
var file_deprecated_proto_depIdxs = []int32{
	0, // 0: example.Deprecated.Obsolete:input_type -> example.ObsoleteRequest
	1, // 1: example.Deprecated.Obsolete:output_type -> example.ObsoleteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deprecated_proto_init() }
func file_deprecated_proto_init() {
	if File_deprecated_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deprecated_proto_rawDesc), len(file_deprecated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deprecated_proto_goTypes,
		DependencyIndexes: file_deprecated_proto_depIdxs,
		MessageInfos:      file_deprecated_proto_msgTypes,
	}.Build()
	File_deprecated_proto = out.File
	file_deprecated_proto_goTypes = nil
	file_deprecated_proto_depIdxs = nil
}
