// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: deprecated.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ObsoleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	Unused string `protobuf:"bytes,1,opt,name=Unused,proto3" json:"Unused,omitempty"`
}

func (x *ObsoleteRequest) Reset() {
	*x = ObsoleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deprecated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObsoleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsoleteRequest) ProtoMessage() {}

func (x *ObsoleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deprecated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsoleteRequest.ProtoReflect.Descriptor instead.
func (*ObsoleteRequest) Descriptor() ([]byte, []int) {
	return file_deprecated_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Do not use.
func (x *ObsoleteRequest) GetUnused() string {
	if x != nil {
		return x.Unused
	}
	return ""
}

type ObsoleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	Unused string `protobuf:"bytes,1,opt,name=Unused,proto3" json:"Unused,omitempty"`
}

func (x *ObsoleteResponse) Reset() {
	*x = ObsoleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deprecated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObsoleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsoleteResponse) ProtoMessage() {}

func (x *ObsoleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deprecated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsoleteResponse.ProtoReflect.Descriptor instead.
func (*ObsoleteResponse) Descriptor() ([]byte, []int) {
	return file_deprecated_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Do not use.
func (x *ObsoleteResponse) GetUnused() string {
	if x != nil {
		return x.Unused
	}
	return ""
}

var File_deprecated_proto protoreflect.FileDescriptor

var file_deprecated_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x2d, 0x0a, 0x0f, 0x4f,
	0x62, 0x73, 0x6f, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x06, 0x55, 0x6e, 0x75, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x06, 0x55, 0x6e, 0x75, 0x73, 0x65, 0x64, 0x22, 0x2e, 0x0a, 0x10, 0x4f, 0x62,
	0x73, 0x6f, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x06, 0x55, 0x6e, 0x75, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x06, 0x55, 0x6e, 0x75, 0x73, 0x65, 0x64, 0x32, 0x57, 0x0a, 0x0a, 0x44, 0x65,
	0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x44, 0x0a, 0x08, 0x4f, 0x62, 0x73, 0x6f,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x4f,
	0x62, 0x73, 0x6f, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x4f, 0x62, 0x73, 0x6f, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x88, 0x02, 0x01, 0x1a, 0x03,
	0x88, 0x02, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_deprecated_proto_rawDescOnce sync.Once
	file_deprecated_proto_rawDescData = file_deprecated_proto_rawDesc
)

func file_deprecated_proto_rawDescGZIP() []byte {
	file_deprecated_proto_rawDescOnce.Do(func() {
		file_deprecated_proto_rawDescData = protoimpl.X.CompressGZIP(file_deprecated_proto_rawDescData)
	})
	return file_deprecated_proto_rawDescData
}

var file_deprecated_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deprecated_proto_goTypes = []interface{}{
	(*ObsoleteRequest)(nil),  // 0: example.ObsoleteRequest
	(*ObsoleteResponse)(nil), // 1: example.ObsoleteResponse
}
var file_deprecated_proto_depIdxs = []int32{
	0, // 0: example.Deprecated.Obsolete:input_type -> example.ObsoleteRequest
	1, // 1: example.Deprecated.Obsolete:output_type -> example.ObsoleteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deprecated_proto_init() }
func file_deprecated_proto_init() {
	if File_deprecated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deprecated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObsoleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deprecated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObsoleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deprecated_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deprecated_proto_goTypes,
		DependencyIndexes: file_deprecated_proto_depIdxs,
		MessageInfos:      file_deprecated_proto_msgTypes,
	}.Build()
	File_deprecated_proto = out.File
	file_deprecated_proto_rawDesc = nil
	file_deprecated_proto_goTypes = nil
	file_deprecated_proto_depIdxs = nil
}
