// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: nested.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Top struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Top) Reset() {
	*x = Top{}
	mi := &file_nested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Top) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top) ProtoMessage() {}

func (x *Top) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top.ProtoReflect.Descriptor instead.
func (*Top) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{0}
}

func (x *Top) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           *Top                   `protobuf:"bytes,1,opt,name=top,proto3" json:"top,omitempty"`
	Inner         *NestedRequest_Inner   `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedRequest) Reset() {
	*x = NestedRequest{}
	mi := &file_nested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedRequest) ProtoMessage() {}

func (x *NestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedRequest.ProtoReflect.Descriptor instead.
func (*NestedRequest) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{1}
}

func (x *NestedRequest) GetTop() *Top {
	if x != nil {
		return x.Top
	}
	return nil
}

func (x *NestedRequest) GetInner() *NestedRequest_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

type OptionalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           *Top                   `protobuf:"bytes,1,opt,name=top,proto3,oneof" json:"top,omitempty"`
	Inner         *OptionalRequest_Inner `protobuf:"bytes,2,opt,name=inner,proto3,oneof" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalRequest) Reset() {
	*x = OptionalRequest{}
	mi := &file_nested_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalRequest) ProtoMessage() {}

func (x *OptionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalRequest.ProtoReflect.Descriptor instead.
func (*OptionalRequest) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{2}
}

func (x *OptionalRequest) GetTop() *Top {
	if x != nil {
		return x.Top
	}
	return nil
}

func (x *OptionalRequest) GetInner() *OptionalRequest_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

type DeepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L0            *DeepRequest_Outer     `protobuf:"bytes,1,opt,name=l0,proto3" json:"l0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepRequest) Reset() {
	*x = DeepRequest{}
	mi := &file_nested_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepRequest) ProtoMessage() {}

func (x *DeepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepRequest.ProtoReflect.Descriptor instead.
func (*DeepRequest) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{3}
}

func (x *DeepRequest) GetL0() *DeepRequest_Outer {
	if x != nil {
		return x.L0
	}
	return nil
}

type OneOfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choose:
	//
	//	*OneOfRequest_Option1
	//	*OneOfRequest_Option2
	//	*OneOfRequest_Option3
	Choose        isOneOfRequest_Choose `protobuf_oneof:"choose"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfRequest) Reset() {
	*x = OneOfRequest{}
	mi := &file_nested_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfRequest) ProtoMessage() {}

func (x *OneOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfRequest.ProtoReflect.Descriptor instead.
func (*OneOfRequest) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{4}
}

func (x *OneOfRequest) GetChoose() isOneOfRequest_Choose {
	if x != nil {
		return x.Choose
	}
	return nil
}

func (x *OneOfRequest) GetOption1() *OneOfRequest_First {
	if x != nil {
		if x, ok := x.Choose.(*OneOfRequest_Option1); ok {
			return x.Option1
		}
	}
	return nil
}

func (x *OneOfRequest) GetOption2() *OneOfRequest_Second {
	if x != nil {
		if x, ok := x.Choose.(*OneOfRequest_Option2); ok {
			return x.Option2
		}
	}
	return nil
}

func (x *OneOfRequest) GetOption3() *OneOfRequest_Third {
	if x != nil {
		if x, ok := x.Choose.(*OneOfRequest_Option3); ok {
			return x.Option3
		}
	}
	return nil
}

type isOneOfRequest_Choose interface {
	isOneOfRequest_Choose()
}

type OneOfRequest_Option1 struct {
	Option1 *OneOfRequest_First `protobuf:"bytes,1,opt,name=option1,proto3,oneof"`
}

type OneOfRequest_Option2 struct {
	Option2 *OneOfRequest_Second `protobuf:"bytes,2,opt,name=option2,proto3,oneof"`
}

type OneOfRequest_Option3 struct {
	Option3 *OneOfRequest_Third `protobuf:"bytes,3,opt,name=option3,proto3,oneof"`
}

func (*OneOfRequest_Option1) isOneOfRequest_Choose() {}

func (*OneOfRequest_Option2) isOneOfRequest_Choose() {}

func (*OneOfRequest_Option3) isOneOfRequest_Choose() {}

type OneOfDeepRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	L0            *OneOfDeepRequest_Outer `protobuf:"bytes,1,opt,name=l0,proto3" json:"l0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest) Reset() {
	*x = OneOfDeepRequest{}
	mi := &file_nested_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest) ProtoMessage() {}

func (x *OneOfDeepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5}
}

func (x *OneOfDeepRequest) GetL0() *OneOfDeepRequest_Outer {
	if x != nil {
		return x.L0
	}
	return nil
}

type NestedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Return        string                 `protobuf:"bytes,1,opt,name=return,proto3" json:"return,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedResponse) Reset() {
	*x = NestedResponse{}
	mi := &file_nested_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedResponse) ProtoMessage() {}

func (x *NestedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedResponse.ProtoReflect.Descriptor instead.
func (*NestedResponse) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{6}
}

func (x *NestedResponse) GetReturn() string {
	if x != nil {
		return x.Return
	}
	return ""
}

type NestedRequest_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedRequest_Inner) Reset() {
	*x = NestedRequest_Inner{}
	mi := &file_nested_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedRequest_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedRequest_Inner) ProtoMessage() {}

func (x *NestedRequest_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedRequest_Inner.ProtoReflect.Descriptor instead.
func (*NestedRequest_Inner) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NestedRequest_Inner) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OptionalRequest_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalRequest_Inner) Reset() {
	*x = OptionalRequest_Inner{}
	mi := &file_nested_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalRequest_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalRequest_Inner) ProtoMessage() {}

func (x *OptionalRequest_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalRequest_Inner.ProtoReflect.Descriptor instead.
func (*OptionalRequest_Inner) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{2, 0}
}

func (x *OptionalRequest_Inner) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type DeepRequest_Outer struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	L1            *DeepRequest_Outer_Middle `protobuf:"bytes,1,opt,name=l1,proto3" json:"l1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepRequest_Outer) Reset() {
	*x = DeepRequest_Outer{}
	mi := &file_nested_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepRequest_Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepRequest_Outer) ProtoMessage() {}

func (x *DeepRequest_Outer) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepRequest_Outer.ProtoReflect.Descriptor instead.
func (*DeepRequest_Outer) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DeepRequest_Outer) GetL1() *DeepRequest_Outer_Middle {
	if x != nil {
		return x.L1
	}
	return nil
}

type DeepRequest_Outer_Middle struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	L2            *DeepRequest_Outer_Middle_Inner `protobuf:"bytes,1,opt,name=l2,proto3" json:"l2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepRequest_Outer_Middle) Reset() {
	*x = DeepRequest_Outer_Middle{}
	mi := &file_nested_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepRequest_Outer_Middle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepRequest_Outer_Middle) ProtoMessage() {}

func (x *DeepRequest_Outer_Middle) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepRequest_Outer_Middle.ProtoReflect.Descriptor instead.
func (*DeepRequest_Outer_Middle) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *DeepRequest_Outer_Middle) GetL2() *DeepRequest_Outer_Middle_Inner {
	if x != nil {
		return x.L2
	}
	return nil
}

type DeepRequest_Outer_Middle_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepRequest_Outer_Middle_Inner) Reset() {
	*x = DeepRequest_Outer_Middle_Inner{}
	mi := &file_nested_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepRequest_Outer_Middle_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepRequest_Outer_Middle_Inner) ProtoMessage() {}

func (x *DeepRequest_Outer_Middle_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepRequest_Outer_Middle_Inner.ProtoReflect.Descriptor instead.
func (*DeepRequest_Outer_Middle_Inner) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{3, 0, 0, 0}
}

func (x *DeepRequest_Outer_Middle_Inner) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OneOfRequest_First struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfRequest_First) Reset() {
	*x = OneOfRequest_First{}
	mi := &file_nested_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfRequest_First) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfRequest_First) ProtoMessage() {}

func (x *OneOfRequest_First) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfRequest_First.ProtoReflect.Descriptor instead.
func (*OneOfRequest_First) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{4, 0}
}

func (x *OneOfRequest_First) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OneOfRequest_Second struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfRequest_Second) Reset() {
	*x = OneOfRequest_Second{}
	mi := &file_nested_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfRequest_Second) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfRequest_Second) ProtoMessage() {}

func (x *OneOfRequest_Second) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfRequest_Second.ProtoReflect.Descriptor instead.
func (*OneOfRequest_Second) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{4, 1}
}

func (x *OneOfRequest_Second) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OneOfRequest_Third struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfRequest_Third) Reset() {
	*x = OneOfRequest_Third{}
	mi := &file_nested_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfRequest_Third) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfRequest_Third) ProtoMessage() {}

func (x *OneOfRequest_Third) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfRequest_Third.ProtoReflect.Descriptor instead.
func (*OneOfRequest_Third) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{4, 2}
}

func (x *OneOfRequest_Third) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OneOfDeepRequest_Outer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choose:
	//
	//	*OneOfDeepRequest_Outer_Option1
	//	*OneOfDeepRequest_Outer_Option2
	//	*OneOfDeepRequest_Outer_Option3
	Choose        isOneOfDeepRequest_Outer_Choose `protobuf_oneof:"choose"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer) Reset() {
	*x = OneOfDeepRequest_Outer{}
	mi := &file_nested_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0}
}

func (x *OneOfDeepRequest_Outer) GetChoose() isOneOfDeepRequest_Outer_Choose {
	if x != nil {
		return x.Choose
	}
	return nil
}

func (x *OneOfDeepRequest_Outer) GetOption1() *OneOfDeepRequest_Outer_First {
	if x != nil {
		if x, ok := x.Choose.(*OneOfDeepRequest_Outer_Option1); ok {
			return x.Option1
		}
	}
	return nil
}

func (x *OneOfDeepRequest_Outer) GetOption2() *OneOfDeepRequest_Outer_Second {
	if x != nil {
		if x, ok := x.Choose.(*OneOfDeepRequest_Outer_Option2); ok {
			return x.Option2
		}
	}
	return nil
}

func (x *OneOfDeepRequest_Outer) GetOption3() *OneOfDeepRequest_Outer_Third {
	if x != nil {
		if x, ok := x.Choose.(*OneOfDeepRequest_Outer_Option3); ok {
			return x.Option3
		}
	}
	return nil
}

type isOneOfDeepRequest_Outer_Choose interface {
	isOneOfDeepRequest_Outer_Choose()
}

type OneOfDeepRequest_Outer_Option1 struct {
	Option1 *OneOfDeepRequest_Outer_First `protobuf:"bytes,1,opt,name=option1,proto3,oneof"`
}

type OneOfDeepRequest_Outer_Option2 struct {
	Option2 *OneOfDeepRequest_Outer_Second `protobuf:"bytes,2,opt,name=option2,proto3,oneof"`
}

type OneOfDeepRequest_Outer_Option3 struct {
	Option3 *OneOfDeepRequest_Outer_Third `protobuf:"bytes,3,opt,name=option3,proto3,oneof"`
}

func (*OneOfDeepRequest_Outer_Option1) isOneOfDeepRequest_Outer_Choose() {}

func (*OneOfDeepRequest_Outer_Option2) isOneOfDeepRequest_Outer_Choose() {}

func (*OneOfDeepRequest_Outer_Option3) isOneOfDeepRequest_Outer_Choose() {}

type OneOfDeepRequest_Outer_Middle struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	L2            *OneOfDeepRequest_Outer_Middle_Inner `protobuf:"bytes,1,opt,name=l2,proto3" json:"l2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_Middle) Reset() {
	*x = OneOfDeepRequest_Outer_Middle{}
	mi := &file_nested_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_Middle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_Middle) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_Middle) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_Middle.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_Middle) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *OneOfDeepRequest_Outer_Middle) GetL2() *OneOfDeepRequest_Outer_Middle_Inner {
	if x != nil {
		return x.L2
	}
	return nil
}

type OneOfDeepRequest_Outer_First struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	L1            *OneOfDeepRequest_Outer_Middle `protobuf:"bytes,1,opt,name=l1,proto3" json:"l1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_First) Reset() {
	*x = OneOfDeepRequest_Outer_First{}
	mi := &file_nested_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_First) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_First) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_First) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_First.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_First) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 1}
}

func (x *OneOfDeepRequest_Outer_First) GetL1() *OneOfDeepRequest_Outer_Middle {
	if x != nil {
		return x.L1
	}
	return nil
}

type OneOfDeepRequest_Outer_Second struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	L1            *OneOfDeepRequest_Outer_Middle `protobuf:"bytes,1,opt,name=l1,proto3" json:"l1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_Second) Reset() {
	*x = OneOfDeepRequest_Outer_Second{}
	mi := &file_nested_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_Second) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_Second) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_Second) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_Second.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_Second) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 2}
}

func (x *OneOfDeepRequest_Outer_Second) GetL1() *OneOfDeepRequest_Outer_Middle {
	if x != nil {
		return x.L1
	}
	return nil
}

type OneOfDeepRequest_Outer_Third struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	L1            *OneOfDeepRequest_Outer_Middle `protobuf:"bytes,1,opt,name=l1,proto3" json:"l1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_Third) Reset() {
	*x = OneOfDeepRequest_Outer_Third{}
	mi := &file_nested_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_Third) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_Third) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_Third) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_Third.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_Third) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 3}
}

func (x *OneOfDeepRequest_Outer_Third) GetL1() *OneOfDeepRequest_Outer_Middle {
	if x != nil {
		return x.L1
	}
	return nil
}

type OneOfDeepRequest_Outer_Middle_Inner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choose:
	//
	//	*OneOfDeepRequest_Outer_Middle_Inner_Option1
	//	*OneOfDeepRequest_Outer_Middle_Inner_Option2
	//	*OneOfDeepRequest_Outer_Middle_Inner_Option3
	Choose        isOneOfDeepRequest_Outer_Middle_Inner_Choose `protobuf_oneof:"choose"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_Middle_Inner) Reset() {
	*x = OneOfDeepRequest_Outer_Middle_Inner{}
	mi := &file_nested_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_Middle_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_Middle_Inner) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_Middle_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_Middle_Inner.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_Middle_Inner) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 0, 0}
}

func (x *OneOfDeepRequest_Outer_Middle_Inner) GetChoose() isOneOfDeepRequest_Outer_Middle_Inner_Choose {
	if x != nil {
		return x.Choose
	}
	return nil
}

func (x *OneOfDeepRequest_Outer_Middle_Inner) GetOption1() *OneOfDeepRequest_Outer_Middle_Inner_First {
	if x != nil {
		if x, ok := x.Choose.(*OneOfDeepRequest_Outer_Middle_Inner_Option1); ok {
			return x.Option1
		}
	}
	return nil
}

func (x *OneOfDeepRequest_Outer_Middle_Inner) GetOption2() *OneOfDeepRequest_Outer_Middle_Inner_Second {
	if x != nil {
		if x, ok := x.Choose.(*OneOfDeepRequest_Outer_Middle_Inner_Option2); ok {
			return x.Option2
		}
	}
	return nil
}

func (x *OneOfDeepRequest_Outer_Middle_Inner) GetOption3() *OneOfDeepRequest_Outer_Middle_Inner_Third {
	if x != nil {
		if x, ok := x.Choose.(*OneOfDeepRequest_Outer_Middle_Inner_Option3); ok {
			return x.Option3
		}
	}
	return nil
}

type isOneOfDeepRequest_Outer_Middle_Inner_Choose interface {
	isOneOfDeepRequest_Outer_Middle_Inner_Choose()
}

type OneOfDeepRequest_Outer_Middle_Inner_Option1 struct {
	Option1 *OneOfDeepRequest_Outer_Middle_Inner_First `protobuf:"bytes,1,opt,name=option1,proto3,oneof"`
}

type OneOfDeepRequest_Outer_Middle_Inner_Option2 struct {
	Option2 *OneOfDeepRequest_Outer_Middle_Inner_Second `protobuf:"bytes,2,opt,name=option2,proto3,oneof"`
}

type OneOfDeepRequest_Outer_Middle_Inner_Option3 struct {
	Option3 *OneOfDeepRequest_Outer_Middle_Inner_Third `protobuf:"bytes,3,opt,name=option3,proto3,oneof"`
}

func (*OneOfDeepRequest_Outer_Middle_Inner_Option1) isOneOfDeepRequest_Outer_Middle_Inner_Choose() {}

func (*OneOfDeepRequest_Outer_Middle_Inner_Option2) isOneOfDeepRequest_Outer_Middle_Inner_Choose() {}

func (*OneOfDeepRequest_Outer_Middle_Inner_Option3) isOneOfDeepRequest_Outer_Middle_Inner_Choose() {}

type OneOfDeepRequest_Outer_Middle_Inner_First struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_First) Reset() {
	*x = OneOfDeepRequest_Outer_Middle_Inner_First{}
	mi := &file_nested_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_First) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_Middle_Inner_First) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_Middle_Inner_First) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_Middle_Inner_First.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_Middle_Inner_First) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 0, 0, 0}
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_First) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OneOfDeepRequest_Outer_Middle_Inner_Second struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Second) Reset() {
	*x = OneOfDeepRequest_Outer_Middle_Inner_Second{}
	mi := &file_nested_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Second) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_Middle_Inner_Second) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Second) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_Middle_Inner_Second.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_Middle_Inner_Second) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 0, 0, 1}
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Second) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OneOfDeepRequest_Outer_Middle_Inner_Third struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Third) Reset() {
	*x = OneOfDeepRequest_Outer_Middle_Inner_Third{}
	mi := &file_nested_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Third) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfDeepRequest_Outer_Middle_Inner_Third) ProtoMessage() {}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Third) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfDeepRequest_Outer_Middle_Inner_Third.ProtoReflect.Descriptor instead.
func (*OneOfDeepRequest_Outer_Middle_Inner_Third) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{5, 0, 0, 0, 2}
}

func (x *OneOfDeepRequest_Outer_Middle_Inner_Third) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_nested_proto protoreflect.FileDescriptor

const file_nested_proto_rawDesc = "" +
	"\n" +
	"\fnested.proto\x12\aexample\"\x1b\n" +
	"\x03Top\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x82\x01\n" +
	"\rNestedRequest\x12\x1e\n" +
	"\x03top\x18\x01 \x01(\v2\f.example.TopR\x03top\x122\n" +
	"\x05inner\x18\x02 \x01(\v2\x1c.example.NestedRequest.InnerR\x05inner\x1a\x1d\n" +
	"\x05Inner\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xb1\x01\n" +
	"\x0fOptionalRequest\x12#\n" +
	"\x03top\x18\x01 \x01(\v2\f.example.TopH\x00R\x03top\x88\x01\x01\x129\n" +
	"\x05inner\x18\x02 \x01(\v2\x1e.example.OptionalRequest.InnerH\x01R\x05inner\x88\x01\x01\x1a,\n" +
	"\x05Inner\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_valueB\x06\n" +
	"\x04_topB\b\n" +
	"\x06_inner\"\xd8\x01\n" +
	"\vDeepRequest\x12*\n" +
	"\x02l0\x18\x01 \x01(\v2\x1a.example.DeepRequest.OuterR\x02l0\x1a\x9c\x01\n" +
	"\x05Outer\x121\n" +
	"\x02l1\x18\x01 \x01(\v2!.example.DeepRequest.Outer.MiddleR\x02l1\x1a`\n" +
	"\x06Middle\x127\n" +
	"\x02l2\x18\x01 \x01(\v2'.example.DeepRequest.Outer.Middle.InnerR\x02l2\x1a\x1d\n" +
	"\x05Inner\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xa2\x02\n" +
	"\fOneOfRequest\x127\n" +
	"\aoption1\x18\x01 \x01(\v2\x1b.example.OneOfRequest.FirstH\x00R\aoption1\x128\n" +
	"\aoption2\x18\x02 \x01(\v2\x1c.example.OneOfRequest.SecondH\x00R\aoption2\x127\n" +
	"\aoption3\x18\x03 \x01(\v2\x1b.example.OneOfRequest.ThirdH\x00R\aoption3\x1a\x1d\n" +
	"\x05First\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a\x1e\n" +
	"\x06Second\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a\x1d\n" +
	"\x05Third\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\b\n" +
	"\x06choose\"\x91\a\n" +
	"\x10OneOfDeepRequest\x12/\n" +
	"\x02l0\x18\x01 \x01(\v2\x1f.example.OneOfDeepRequest.OuterR\x02l0\x1a\xcb\x06\n" +
	"\x05Outer\x12A\n" +
	"\aoption1\x18\x01 \x01(\v2%.example.OneOfDeepRequest.Outer.FirstH\x00R\aoption1\x12B\n" +
	"\aoption2\x18\x02 \x01(\v2&.example.OneOfDeepRequest.Outer.SecondH\x00R\aoption2\x12A\n" +
	"\aoption3\x18\x03 \x01(\v2%.example.OneOfDeepRequest.Outer.ThirdH\x00R\aoption3\x1a\xa9\x03\n" +
	"\x06Middle\x12<\n" +
	"\x02l2\x18\x01 \x01(\v2,.example.OneOfDeepRequest.Outer.Middle.InnerR\x02l2\x1a\xe0\x02\n" +
	"\x05Inner\x12N\n" +
	"\aoption1\x18\x01 \x01(\v22.example.OneOfDeepRequest.Outer.Middle.Inner.FirstH\x00R\aoption1\x12O\n" +
	"\aoption2\x18\x02 \x01(\v23.example.OneOfDeepRequest.Outer.Middle.Inner.SecondH\x00R\aoption2\x12N\n" +
	"\aoption3\x18\x03 \x01(\v22.example.OneOfDeepRequest.Outer.Middle.Inner.ThirdH\x00R\aoption3\x1a\x1d\n" +
	"\x05First\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a\x1e\n" +
	"\x06Second\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a\x1d\n" +
	"\x05Third\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\b\n" +
	"\x06choose\x1a?\n" +
	"\x05First\x126\n" +
	"\x02l1\x18\x01 \x01(\v2&.example.OneOfDeepRequest.Outer.MiddleR\x02l1\x1a@\n" +
	"\x06Second\x126\n" +
	"\x02l1\x18\x01 \x01(\v2&.example.OneOfDeepRequest.Outer.MiddleR\x02l1\x1a?\n" +
	"\x05Third\x126\n" +
	"\x02l1\x18\x01 \x01(\v2&.example.OneOfDeepRequest.Outer.MiddleR\x02l1B\b\n" +
	"\x06choose\"(\n" +
	"\x0eNestedResponse\x12\x16\n" +
	"\x06return\x18\x01 \x01(\tR\x06return2\xbc\x02\n" +
	"\x06Nested\x126\n" +
	"\x03Get\x12\x16.example.NestedRequest\x1a\x17.example.NestedResponse\x12@\n" +
	"\vGetOptional\x12\x18.example.OptionalRequest\x1a\x17.example.NestedResponse\x128\n" +
	"\aGetDeep\x12\x14.example.DeepRequest\x1a\x17.example.NestedResponse\x12:\n" +
	"\bGetOneOf\x12\x15.example.OneOfRequest\x1a\x17.example.NestedResponse\x12B\n" +
	"\fGetOneOfDeep\x12\x19.example.OneOfDeepRequest\x1a\x17.example.NestedResponseB\x06Z\x04.;pbb\x06proto3"

var (
	file_nested_proto_rawDescOnce sync.Once
	file_nested_proto_rawDescData []byte
)

func file_nested_proto_rawDescGZIP() []byte {
	file_nested_proto_rawDescOnce.Do(func() {
		file_nested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nested_proto_rawDesc), len(file_nested_proto_rawDesc)))
	})
	return file_nested_proto_rawDescData
}

var file_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_nested_proto_goTypes = []any{
	(*Top)(nil),                                        // 0: example.Top
	(*NestedRequest)(nil),                              // 1: example.NestedRequest
	(*OptionalRequest)(nil),                            // 2: example.OptionalRequest
	(*DeepRequest)(nil),                                // 3: example.DeepRequest
	(*OneOfRequest)(nil),                               // 4: example.OneOfRequest
	(*OneOfDeepRequest)(nil),                           // 5: example.OneOfDeepRequest
	(*NestedResponse)(nil),                             // 6: example.NestedResponse
	(*NestedRequest_Inner)(nil),                        // 7: example.NestedRequest.Inner
	(*OptionalRequest_Inner)(nil),                      // 8: example.OptionalRequest.Inner
	(*DeepRequest_Outer)(nil),                          // 9: example.DeepRequest.Outer
	(*DeepRequest_Outer_Middle)(nil),                   // 10: example.DeepRequest.Outer.Middle
	(*DeepRequest_Outer_Middle_Inner)(nil),             // 11: example.DeepRequest.Outer.Middle.Inner
	(*OneOfRequest_First)(nil),                         // 12: example.OneOfRequest.First
	(*OneOfRequest_Second)(nil),                        // 13: example.OneOfRequest.Second
	(*OneOfRequest_Third)(nil),                         // 14: example.OneOfRequest.Third
	(*OneOfDeepRequest_Outer)(nil),                     // 15: example.OneOfDeepRequest.Outer
	(*OneOfDeepRequest_Outer_Middle)(nil),              // 16: example.OneOfDeepRequest.Outer.Middle
	(*OneOfDeepRequest_Outer_First)(nil),               // 17: example.OneOfDeepRequest.Outer.First
	(*OneOfDeepRequest_Outer_Second)(nil),              // 18: example.OneOfDeepRequest.Outer.Second
	(*OneOfDeepRequest_Outer_Third)(nil),               // 19: example.OneOfDeepRequest.Outer.Third
	(*OneOfDeepRequest_Outer_Middle_Inner)(nil),        // 20: example.OneOfDeepRequest.Outer.Middle.Inner
	(*OneOfDeepRequest_Outer_Middle_Inner_First)(nil),  // 21: example.OneOfDeepRequest.Outer.Middle.Inner.First
	(*OneOfDeepRequest_Outer_Middle_Inner_Second)(nil), // 22: example.OneOfDeepRequest.Outer.Middle.Inner.Second
	(*OneOfDeepRequest_Outer_Middle_Inner_Third)(nil),  // 23: example.OneOfDeepRequest.Outer.Middle.Inner.Third
}
var file_nested_proto_depIdxs = []int32{
	0,  // 0: example.NestedRequest.top:type_name -> example.Top
	7,  // 1: example.NestedRequest.inner:type_name -> example.NestedRequest.Inner
	0,  // 2: example.OptionalRequest.top:type_name -> example.Top
	8,  // 3: example.OptionalRequest.inner:type_name -> example.OptionalRequest.Inner
	9,  // 4: example.DeepRequest.l0:type_name -> example.DeepRequest.Outer
	12, // 5: example.OneOfRequest.option1:type_name -> example.OneOfRequest.First
	13, // 6: example.OneOfRequest.option2:type_name -> example.OneOfRequest.Second
	14, // 7: example.OneOfRequest.option3:type_name -> example.OneOfRequest.Third
	15, // 8: example.OneOfDeepRequest.l0:type_name -> example.OneOfDeepRequest.Outer
	10, // 9: example.DeepRequest.Outer.l1:type_name -> example.DeepRequest.Outer.Middle
	11, // 10: example.DeepRequest.Outer.Middle.l2:type_name -> example.DeepRequest.Outer.Middle.Inner
	17, // 11: example.OneOfDeepRequest.Outer.option1:type_name -> example.OneOfDeepRequest.Outer.First
	18, // 12: example.OneOfDeepRequest.Outer.option2:type_name -> example.OneOfDeepRequest.Outer.Second
	19, // 13: example.OneOfDeepRequest.Outer.option3:type_name -> example.OneOfDeepRequest.Outer.Third
	20, // 14: example.OneOfDeepRequest.Outer.Middle.l2:type_name -> example.OneOfDeepRequest.Outer.Middle.Inner
	16, // 15: example.OneOfDeepRequest.Outer.First.l1:type_name -> example.OneOfDeepRequest.Outer.Middle
	16, // 16: example.OneOfDeepRequest.Outer.Second.l1:type_name -> example.OneOfDeepRequest.Outer.Middle
	16, // 17: example.OneOfDeepRequest.Outer.Third.l1:type_name -> example.OneOfDeepRequest.Outer.Middle
	21, // 18: example.OneOfDeepRequest.Outer.Middle.Inner.option1:type_name -> example.OneOfDeepRequest.Outer.Middle.Inner.First
	22, // 19: example.OneOfDeepRequest.Outer.Middle.Inner.option2:type_name -> example.OneOfDeepRequest.Outer.Middle.Inner.Second
	23, // 20: example.OneOfDeepRequest.Outer.Middle.Inner.option3:type_name -> example.OneOfDeepRequest.Outer.Middle.Inner.Third
	1,  // 21: example.Nested.Get:input_type -> example.NestedRequest
	2,  // 22: example.Nested.GetOptional:input_type -> example.OptionalRequest
	3,  // 23: example.Nested.GetDeep:input_type -> example.DeepRequest
	4,  // 24: example.Nested.GetOneOf:input_type -> example.OneOfRequest
	5,  // 25: example.Nested.GetOneOfDeep:input_type -> example.OneOfDeepRequest
	6,  // 26: example.Nested.Get:output_type -> example.NestedResponse
	6,  // 27: example.Nested.GetOptional:output_type -> example.NestedResponse
	6,  // 28: example.Nested.GetDeep:output_type -> example.NestedResponse
	6,  // 29: example.Nested.GetOneOf:output_type -> example.NestedResponse
	6,  // 30: example.Nested.GetOneOfDeep:output_type -> example.NestedResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_nested_proto_init() }
func file_nested_proto_init() {
	if File_nested_proto != nil {
		return
	}
	file_nested_proto_msgTypes[2].OneofWrappers = []any{}
	file_nested_proto_msgTypes[4].OneofWrappers = []any{
		(*OneOfRequest_Option1)(nil),
		(*OneOfRequest_Option2)(nil),
		(*OneOfRequest_Option3)(nil),
	}
	file_nested_proto_msgTypes[8].OneofWrappers = []any{}
	file_nested_proto_msgTypes[15].OneofWrappers = []any{
		(*OneOfDeepRequest_Outer_Option1)(nil),
		(*OneOfDeepRequest_Outer_Option2)(nil),
		(*OneOfDeepRequest_Outer_Option3)(nil),
	}
	file_nested_proto_msgTypes[20].OneofWrappers = []any{
		(*OneOfDeepRequest_Outer_Middle_Inner_Option1)(nil),
		(*OneOfDeepRequest_Outer_Middle_Inner_Option2)(nil),
		(*OneOfDeepRequest_Outer_Middle_Inner_Option3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nested_proto_rawDesc), len(file_nested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nested_proto_goTypes,
		DependencyIndexes: file_nested_proto_depIdxs,
		MessageInfos:      file_nested_proto_msgTypes,
	}.Build()
	File_nested_proto = out.File
	file_nested_proto_goTypes = nil
	file_nested_proto_depIdxs = nil
}
