// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: oneof.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Oneof_Fetch_FullMethodName       = "/example.Oneof/Fetch"
	Oneof_FetchNested_FullMethodName = "/example.Oneof/FetchNested"
)

// OneofClient is the client API for Oneof service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OneofClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	FetchNested(ctx context.Context, in *FetchNestedRequest, opts ...grpc.CallOption) (*FetchResponse, error)
}

type oneofClient struct {
	cc grpc.ClientConnInterface
}

func NewOneofClient(cc grpc.ClientConnInterface) OneofClient {
	return &oneofClient{cc}
}

func (c *oneofClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, Oneof_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oneofClient) FetchNested(ctx context.Context, in *FetchNestedRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, Oneof_FetchNested_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OneofServer is the server API for Oneof service.
// All implementations must embed UnimplementedOneofServer
// for forward compatibility.
type OneofServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	FetchNested(context.Context, *FetchNestedRequest) (*FetchResponse, error)
	mustEmbedUnimplementedOneofServer()
}

// UnimplementedOneofServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOneofServer struct{}

func (UnimplementedOneofServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedOneofServer) FetchNested(context.Context, *FetchNestedRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNested not implemented")
}
func (UnimplementedOneofServer) mustEmbedUnimplementedOneofServer() {}
func (UnimplementedOneofServer) testEmbeddedByValue()               {}

// UnsafeOneofServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OneofServer will
// result in compilation errors.
type UnsafeOneofServer interface {
	mustEmbedUnimplementedOneofServer()
}

func RegisterOneofServer(s grpc.ServiceRegistrar, srv OneofServer) {
	// If the following call pancis, it indicates UnimplementedOneofServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Oneof_ServiceDesc, srv)
}

func _Oneof_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneofServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oneof_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneofServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oneof_FetchNested_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchNestedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneofServer).FetchNested(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Oneof_FetchNested_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneofServer).FetchNested(ctx, req.(*FetchNestedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Oneof_ServiceDesc is the grpc.ServiceDesc for Oneof service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oneof_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.Oneof",
	HandlerType: (*OneofServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Oneof_Fetch_Handler,
		},
		{
			MethodName: "FetchNested",
			Handler:    _Oneof_FetchNested_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oneof.proto",
}
