// Code generated by protoc-gen-cobra. DO NOT EDIT.

package pb

import (
	client "github.com/NathanBaulch/protoc-gen-cobra/client"
	flag "github.com/NathanBaulch/protoc-gen-cobra/flag"
	iocodec "github.com/NathanBaulch/protoc-gen-cobra/iocodec"
	cobra "github.com/spf13/cobra"
	grpc "google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
)

func TypesClientCommand(options ...client.Option) *cobra.Command {
	cfg := client.NewConfig(options...)
	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("Types"),
		Short: "Types service client",
		Long:  "",
	}
	cfg.BindFlags(cmd.PersistentFlags())
	cmd.AddCommand(
		_TypesEchoCommand(cfg),
	)
	return cmd
}

func _TypesEchoCommand(cfg *client.Config) *cobra.Command {
	req := &Sound{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("Echo"),
		Short: "Echo RPC client",
		Long:  "",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "Types"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "Types", "Echo"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewTypesClient(cc)
				v := &Sound{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.Echo(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().Float64Var(&req.Double, cfg.FlagNamer("Double"), 0, "")
	cmd.PersistentFlags().Float32Var(&req.Float, cfg.FlagNamer("Float"), 0, "")
	cmd.PersistentFlags().Int32Var(&req.Int32, cfg.FlagNamer("Int32"), 0, "")
	cmd.PersistentFlags().Int64Var(&req.Int64, cfg.FlagNamer("Int64"), 0, "")
	cmd.PersistentFlags().Uint32Var(&req.Uint32, cfg.FlagNamer("Uint32"), 0, "")
	cmd.PersistentFlags().Uint64Var(&req.Uint64, cfg.FlagNamer("Uint64"), 0, "")
	cmd.PersistentFlags().Int32Var(&req.Sint32, cfg.FlagNamer("Sint32"), 0, "")
	cmd.PersistentFlags().Int64Var(&req.Sint64, cfg.FlagNamer("Sint64"), 0, "")
	cmd.PersistentFlags().Uint32Var(&req.Fixed32, cfg.FlagNamer("Fixed32"), 0, "")
	cmd.PersistentFlags().Uint64Var(&req.Fixed64, cfg.FlagNamer("Fixed64"), 0, "")
	cmd.PersistentFlags().Int32Var(&req.Sfixed32, cfg.FlagNamer("Sfixed32"), 0, "")
	cmd.PersistentFlags().Int64Var(&req.Sfixed64, cfg.FlagNamer("Sfixed64"), 0, "")
	cmd.PersistentFlags().BoolVar(&req.Bool, cfg.FlagNamer("Bool"), false, "")
	cmd.PersistentFlags().StringVar(&req.String_, cfg.FlagNamer("String_"), "", "")
	flag.BytesBase64Var(cmd.PersistentFlags(), &req.Bytes, cfg.FlagNamer("Bytes"), "")
	flag.EnumVar(cmd.PersistentFlags(), &req.NestedEnum, cfg.FlagNamer("NestedEnum"), "")
	flag.EnumVar(cmd.PersistentFlags(), &req.GlobalEnum, cfg.FlagNamer("GlobalEnum"), "")
	cmd.PersistentFlags().Float64SliceVar(&req.ListDouble, cfg.FlagNamer("ListDouble"), nil, "")
	cmd.PersistentFlags().Float32SliceVar(&req.ListFloat, cfg.FlagNamer("ListFloat"), nil, "")
	cmd.PersistentFlags().Int32SliceVar(&req.ListInt32, cfg.FlagNamer("ListInt32"), nil, "")
	cmd.PersistentFlags().Int64SliceVar(&req.ListInt64, cfg.FlagNamer("ListInt64"), nil, "")
	flag.Uint32SliceVar(cmd.PersistentFlags(), &req.ListUint32, cfg.FlagNamer("ListUint32"), "")
	flag.Uint64SliceVar(cmd.PersistentFlags(), &req.ListUint64, cfg.FlagNamer("ListUint64"), "")
	cmd.PersistentFlags().Int32SliceVar(&req.ListSint32, cfg.FlagNamer("ListSint32"), nil, "")
	cmd.PersistentFlags().Int64SliceVar(&req.ListSint64, cfg.FlagNamer("ListSint64"), nil, "")
	flag.Uint32SliceVar(cmd.PersistentFlags(), &req.ListFixed32, cfg.FlagNamer("ListFixed32"), "")
	flag.Uint64SliceVar(cmd.PersistentFlags(), &req.ListFixed64, cfg.FlagNamer("ListFixed64"), "")
	cmd.PersistentFlags().Int32SliceVar(&req.ListSfixed32, cfg.FlagNamer("ListSfixed32"), nil, "")
	cmd.PersistentFlags().Int64SliceVar(&req.ListSfixed64, cfg.FlagNamer("ListSfixed64"), nil, "")
	cmd.PersistentFlags().BoolSliceVar(&req.ListBool, cfg.FlagNamer("ListBool"), nil, "")
	cmd.PersistentFlags().StringSliceVar(&req.ListString, cfg.FlagNamer("ListString"), nil, "")
	flag.BytesBase64SliceVar(cmd.PersistentFlags(), &req.ListBytes, cfg.FlagNamer("ListBytes"), "")
	flag.EnumSliceVar(cmd.PersistentFlags(), &req.ListNestedEnum, cfg.FlagNamer("ListNestedEnum"), "")
	flag.EnumSliceVar(cmd.PersistentFlags(), &req.ListGlobalEnum, cfg.FlagNamer("ListGlobalEnum"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseFloat64E, &req.MapStringDouble, cfg.FlagNamer("MapStringDouble"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseFloat32E, &req.MapStringFloat, cfg.FlagNamer("MapStringFloat"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseInt32E, &req.MapStringInt32, cfg.FlagNamer("MapStringInt32"), "")
	cmd.PersistentFlags().StringToInt64Var(&req.MapStringInt64, cfg.FlagNamer("MapStringInt64"), nil, "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseUint32E, &req.MapStringUint32, cfg.FlagNamer("MapStringUint32"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseUint64E, &req.MapStringUint64, cfg.FlagNamer("MapStringUint64"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseInt32E, &req.MapStringSint32, cfg.FlagNamer("MapStringSint32"), "")
	cmd.PersistentFlags().StringToInt64Var(&req.MapStringSint64, cfg.FlagNamer("MapStringSint64"), nil, "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseUint32E, &req.MapStringFixed32, cfg.FlagNamer("MapStringFixed32"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseUint64E, &req.MapStringFixed64, cfg.FlagNamer("MapStringFixed64"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseInt32E, &req.MapStringSfixed32, cfg.FlagNamer("MapStringSfixed32"), "")
	cmd.PersistentFlags().StringToInt64Var(&req.MapStringSfixed64, cfg.FlagNamer("MapStringSfixed64"), nil, "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseBoolE, &req.MapStringBool, cfg.FlagNamer("MapStringBool"), "")
	cmd.PersistentFlags().StringToStringVar(&req.MapStringString, cfg.FlagNamer("MapStringString"), nil, "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseBytesBase64E, &req.MapStringBytes, cfg.FlagNamer("MapStringBytes"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseEnumE[Sound_NestedEnum], &req.MapStringNestedEnum, cfg.FlagNamer("MapStringNestedEnum"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseEnumE[GlobalEnum], &req.MapStringGlobalEnum, cfg.FlagNamer("MapStringGlobalEnum"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseInt32E, flag.ParseStringE, &req.MapInt32String, cfg.FlagNamer("MapInt32String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseInt64E, flag.ParseStringE, &req.MapInt64String, cfg.FlagNamer("MapInt64String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseUint32E, flag.ParseStringE, &req.MapUint32String, cfg.FlagNamer("MapUint32String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseUint64E, flag.ParseStringE, &req.MapUint64String, cfg.FlagNamer("MapUint64String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseInt32E, flag.ParseStringE, &req.MapSint32String, cfg.FlagNamer("MapSint32String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseInt64E, flag.ParseStringE, &req.MapSint64String, cfg.FlagNamer("MapSint64String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseUint32E, flag.ParseStringE, &req.MapFixed32String, cfg.FlagNamer("MapFixed32String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseUint64E, flag.ParseStringE, &req.MapFixed64String, cfg.FlagNamer("MapFixed64String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseInt32E, flag.ParseStringE, &req.MapSfixed32String, cfg.FlagNamer("MapSfixed32String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseInt64E, flag.ParseStringE, &req.MapSfixed64String, cfg.FlagNamer("MapSfixed64String"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseBoolE, flag.ParseStringE, &req.MapBoolString, cfg.FlagNamer("MapBoolString"), "")
	flag.TimestampVar(cmd.PersistentFlags(), &req.Timestamp, cfg.FlagNamer("Timestamp"), "")
	flag.DurationVar(cmd.PersistentFlags(), &req.Duration, cfg.FlagNamer("Duration"), "")
	flag.BoolWrapperVar(cmd.PersistentFlags(), &req.WrapperBool, cfg.FlagNamer("WrapperBool"), "")
	flag.BytesBase64WrapperVar(cmd.PersistentFlags(), &req.WrapperBytes, cfg.FlagNamer("WrapperBytes"), "")
	flag.DoubleWrapperVar(cmd.PersistentFlags(), &req.WrapperDouble, cfg.FlagNamer("WrapperDouble"), "")
	flag.FloatWrapperVar(cmd.PersistentFlags(), &req.WrapperFloat, cfg.FlagNamer("WrapperFloat"), "")
	flag.Int32WrapperVar(cmd.PersistentFlags(), &req.WrapperInt32, cfg.FlagNamer("WrapperInt32"), "")
	flag.Int64WrapperVar(cmd.PersistentFlags(), &req.WrapperInt64, cfg.FlagNamer("WrapperInt64"), "")
	flag.StringWrapperVar(cmd.PersistentFlags(), &req.WrapperString, cfg.FlagNamer("WrapperString"), "")
	flag.UInt32WrapperVar(cmd.PersistentFlags(), &req.WrapperUint32, cfg.FlagNamer("WrapperUint32"), "")
	flag.UInt64WrapperVar(cmd.PersistentFlags(), &req.WrapperUint64, cfg.FlagNamer("WrapperUint64"), "")
	flag.TimestampSliceVar(cmd.PersistentFlags(), &req.ListTimestamp, cfg.FlagNamer("ListTimestamp"), "")
	flag.DurationSliceVar(cmd.PersistentFlags(), &req.ListDuration, cfg.FlagNamer("ListDuration"), "")
	flag.BoolWrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperBool, cfg.FlagNamer("ListWrapperBool"), "")
	flag.BytesBase64WrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperBytes, cfg.FlagNamer("ListWrapperBytes"), "")
	flag.DoubleWrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperDouble, cfg.FlagNamer("ListWrapperDouble"), "")
	flag.FloatWrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperFloat, cfg.FlagNamer("ListWrapperFloat"), "")
	flag.Int32WrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperInt32, cfg.FlagNamer("ListWrapperInt32"), "")
	flag.Int64WrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperInt64, cfg.FlagNamer("ListWrapperInt64"), "")
	flag.StringWrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperString, cfg.FlagNamer("ListWrapperString"), "")
	flag.UInt32WrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperUint32, cfg.FlagNamer("ListWrapperUint32"), "")
	flag.UInt64WrapperSliceVar(cmd.PersistentFlags(), &req.ListWrapperUint64, cfg.FlagNamer("ListWrapperUint64"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseTimestampE, &req.MapStringTimestamp, cfg.FlagNamer("MapStringTimestamp"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseDurationE, &req.MapStringDuration, cfg.FlagNamer("MapStringDuration"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseBoolWrapperE, &req.MapStringWrapperBool, cfg.FlagNamer("MapStringWrapperBool"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseBytesBase64WrapperE, &req.MapStringWrapperBytes, cfg.FlagNamer("MapStringWrapperBytes"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseDoubleWrapperE, &req.MapStringWrapperDouble, cfg.FlagNamer("MapStringWrapperDouble"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseFloatWrapperE, &req.MapStringWrapperFloat, cfg.FlagNamer("MapStringWrapperFloat"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseInt32WrapperE, &req.MapStringWrapperInt32, cfg.FlagNamer("MapStringWrapperInt32"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseInt64WrapperE, &req.MapStringWrapperInt64, cfg.FlagNamer("MapStringWrapperInt64"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseStringWrapperE, &req.MapStringWrapperString, cfg.FlagNamer("MapStringWrapperString"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseUInt32WrapperE, &req.MapStringWrapperUint32, cfg.FlagNamer("MapStringWrapperUint32"), "")
	flag.MapVar(cmd.PersistentFlags(), flag.ParseStringE, flag.ParseUInt64WrapperE, &req.MapStringWrapperUint64, cfg.FlagNamer("MapStringWrapperUint64"), "")

	return cmd
}
