// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalEnum int32

const (
	GlobalEnum_MON GlobalEnum = 0
	GlobalEnum_TUE GlobalEnum = 1
	GlobalEnum_WED GlobalEnum = 2
)

// Enum value maps for GlobalEnum.
var (
	GlobalEnum_name = map[int32]string{
		0: "MON",
		1: "TUE",
		2: "WED",
	}
	GlobalEnum_value = map[string]int32{
		"MON": 0,
		"TUE": 1,
		"WED": 2,
	}
)

func (x GlobalEnum) Enum() *GlobalEnum {
	p := new(GlobalEnum)
	*p = x
	return p
}

func (x GlobalEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (GlobalEnum) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x GlobalEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalEnum.Descriptor instead.
func (GlobalEnum) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type Sound_NestedEnum int32

const (
	Sound_JAN Sound_NestedEnum = 0
	Sound_FEB Sound_NestedEnum = 1
	Sound_MAR Sound_NestedEnum = 2
)

// Enum value maps for Sound_NestedEnum.
var (
	Sound_NestedEnum_name = map[int32]string{
		0: "JAN",
		1: "FEB",
		2: "MAR",
	}
	Sound_NestedEnum_value = map[string]int32{
		"JAN": 0,
		"FEB": 1,
		"MAR": 2,
	}
)

func (x Sound_NestedEnum) Enum() *Sound_NestedEnum {
	p := new(Sound_NestedEnum)
	*p = x
	return p
}

func (x Sound_NestedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sound_NestedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (Sound_NestedEnum) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x Sound_NestedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sound_NestedEnum.Descriptor instead.
func (Sound_NestedEnum) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0, 0}
}

type Sound struct {
	state                  protoimpl.MessageState             `protogen:"open.v1"`
	Double                 float64                            `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float                  float32                            `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32                  int32                              `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64                  int64                              `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32                 uint32                             `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64                 uint64                             `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32                 int32                              `protobuf:"zigzag32,7,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64                 int64                              `protobuf:"zigzag64,8,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32                uint32                             `protobuf:"fixed32,9,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64                uint64                             `protobuf:"fixed64,10,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32               int32                              `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64               int64                              `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool                   bool                               `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	String_                string                             `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes                  []byte                             `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	NestedEnum             Sound_NestedEnum                   `protobuf:"varint,16,opt,name=nested_enum,json=nestedEnum,proto3,enum=example.Sound_NestedEnum" json:"nested_enum,omitempty"`
	GlobalEnum             GlobalEnum                         `protobuf:"varint,17,opt,name=global_enum,json=globalEnum,proto3,enum=example.GlobalEnum" json:"global_enum,omitempty"`
	NestedMsg              *Sound_NestedMessage               `protobuf:"bytes,18,opt,name=nested_msg,json=nestedMsg,proto3" json:"nested_msg,omitempty"`
	GlobalMsg              *GlobalMessage                     `protobuf:"bytes,19,opt,name=global_msg,json=globalMsg,proto3" json:"global_msg,omitempty"`
	ListDouble             []float64                          `protobuf:"fixed64,21,rep,packed,name=list_double,json=listDouble,proto3" json:"list_double,omitempty"`
	ListFloat              []float32                          `protobuf:"fixed32,22,rep,packed,name=list_float,json=listFloat,proto3" json:"list_float,omitempty"`
	ListInt32              []int32                            `protobuf:"varint,23,rep,packed,name=list_int32,json=listInt32,proto3" json:"list_int32,omitempty"`
	ListInt64              []int64                            `protobuf:"varint,24,rep,packed,name=list_int64,json=listInt64,proto3" json:"list_int64,omitempty"`
	ListUint32             []uint32                           `protobuf:"varint,25,rep,packed,name=list_uint32,json=listUint32,proto3" json:"list_uint32,omitempty"`
	ListUint64             []uint64                           `protobuf:"varint,26,rep,packed,name=list_uint64,json=listUint64,proto3" json:"list_uint64,omitempty"`
	ListSint32             []int32                            `protobuf:"zigzag32,27,rep,packed,name=list_sint32,json=listSint32,proto3" json:"list_sint32,omitempty"`
	ListSint64             []int64                            `protobuf:"zigzag64,28,rep,packed,name=list_sint64,json=listSint64,proto3" json:"list_sint64,omitempty"`
	ListFixed32            []uint32                           `protobuf:"fixed32,29,rep,packed,name=list_fixed32,json=listFixed32,proto3" json:"list_fixed32,omitempty"`
	ListFixed64            []uint64                           `protobuf:"fixed64,30,rep,packed,name=list_fixed64,json=listFixed64,proto3" json:"list_fixed64,omitempty"`
	ListSfixed32           []int32                            `protobuf:"fixed32,31,rep,packed,name=list_sfixed32,json=listSfixed32,proto3" json:"list_sfixed32,omitempty"`
	ListSfixed64           []int64                            `protobuf:"fixed64,32,rep,packed,name=list_sfixed64,json=listSfixed64,proto3" json:"list_sfixed64,omitempty"`
	ListBool               []bool                             `protobuf:"varint,33,rep,packed,name=list_bool,json=listBool,proto3" json:"list_bool,omitempty"`
	ListString             []string                           `protobuf:"bytes,34,rep,name=list_string,json=listString,proto3" json:"list_string,omitempty"`
	ListBytes              [][]byte                           `protobuf:"bytes,35,rep,name=list_bytes,json=listBytes,proto3" json:"list_bytes,omitempty"`
	ListNestedEnum         []Sound_NestedEnum                 `protobuf:"varint,36,rep,packed,name=list_nested_enum,json=listNestedEnum,proto3,enum=example.Sound_NestedEnum" json:"list_nested_enum,omitempty"`
	ListGlobalEnum         []GlobalEnum                       `protobuf:"varint,37,rep,packed,name=list_global_enum,json=listGlobalEnum,proto3,enum=example.GlobalEnum" json:"list_global_enum,omitempty"`
	ListNestedMsg          []*Sound_NestedMessage             `protobuf:"bytes,38,rep,name=list_nested_msg,json=listNestedMsg,proto3" json:"list_nested_msg,omitempty"`
	ListGlobalMsg          []*GlobalMessage                   `protobuf:"bytes,39,rep,name=list_global_msg,json=listGlobalMsg,proto3" json:"list_global_msg,omitempty"`
	MapStringDouble        map[string]float64                 `protobuf:"bytes,41,rep,name=map_string_double,json=mapStringDouble,proto3" json:"map_string_double,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	MapStringFloat         map[string]float32                 `protobuf:"bytes,42,rep,name=map_string_float,json=mapStringFloat,proto3" json:"map_string_float,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	MapStringInt32         map[string]int32                   `protobuf:"bytes,43,rep,name=map_string_int32,json=mapStringInt32,proto3" json:"map_string_int32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapStringInt64         map[string]int64                   `protobuf:"bytes,44,rep,name=map_string_int64,json=mapStringInt64,proto3" json:"map_string_int64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapStringUint32        map[string]uint32                  `protobuf:"bytes,45,rep,name=map_string_uint32,json=mapStringUint32,proto3" json:"map_string_uint32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapStringUint64        map[string]uint64                  `protobuf:"bytes,46,rep,name=map_string_uint64,json=mapStringUint64,proto3" json:"map_string_uint64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapStringSint32        map[string]int32                   `protobuf:"bytes,47,rep,name=map_string_sint32,json=mapStringSint32,proto3" json:"map_string_sint32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"zigzag32,2,opt,name=value"`
	MapStringSint64        map[string]int64                   `protobuf:"bytes,48,rep,name=map_string_sint64,json=mapStringSint64,proto3" json:"map_string_sint64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"zigzag64,2,opt,name=value"`
	MapStringFixed32       map[string]uint32                  `protobuf:"bytes,49,rep,name=map_string_fixed32,json=mapStringFixed32,proto3" json:"map_string_fixed32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	MapStringFixed64       map[string]uint64                  `protobuf:"bytes,50,rep,name=map_string_fixed64,json=mapStringFixed64,proto3" json:"map_string_fixed64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	MapStringSfixed32      map[string]int32                   `protobuf:"bytes,51,rep,name=map_string_sfixed32,json=mapStringSfixed32,proto3" json:"map_string_sfixed32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	MapStringSfixed64      map[string]int64                   `protobuf:"bytes,52,rep,name=map_string_sfixed64,json=mapStringSfixed64,proto3" json:"map_string_sfixed64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	MapStringBool          map[string]bool                    `protobuf:"bytes,53,rep,name=map_string_bool,json=mapStringBool,proto3" json:"map_string_bool,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapStringString        map[string]string                  `protobuf:"bytes,54,rep,name=map_string_string,json=mapStringString,proto3" json:"map_string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringBytes         map[string][]byte                  `protobuf:"bytes,55,rep,name=map_string_bytes,json=mapStringBytes,proto3" json:"map_string_bytes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringNestedEnum    map[string]Sound_NestedEnum        `protobuf:"bytes,56,rep,name=map_string_nested_enum,json=mapStringNestedEnum,proto3" json:"map_string_nested_enum,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=example.Sound_NestedEnum"`
	MapStringGlobalEnum    map[string]GlobalEnum              `protobuf:"bytes,57,rep,name=map_string_global_enum,json=mapStringGlobalEnum,proto3" json:"map_string_global_enum,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=example.GlobalEnum"`
	MapStringNestedMsg     map[string]*Sound_NestedMessage    `protobuf:"bytes,58,rep,name=map_string_nested_msg,json=mapStringNestedMsg,proto3" json:"map_string_nested_msg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringGlobalMsg     map[string]*GlobalMessage          `protobuf:"bytes,59,rep,name=map_string_global_msg,json=mapStringGlobalMsg,proto3" json:"map_string_global_msg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt32String         map[int32]string                   `protobuf:"bytes,61,rep,name=map_int32_string,json=mapInt32String,proto3" json:"map_int32_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt64String         map[int64]string                   `protobuf:"bytes,62,rep,name=map_int64_string,json=mapInt64String,proto3" json:"map_int64_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapUint32String        map[uint32]string                  `protobuf:"bytes,63,rep,name=map_uint32_string,json=mapUint32String,proto3" json:"map_uint32_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapUint64String        map[uint64]string                  `protobuf:"bytes,64,rep,name=map_uint64_string,json=mapUint64String,proto3" json:"map_uint64_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapSint32String        map[int32]string                   `protobuf:"bytes,65,rep,name=map_sint32_string,json=mapSint32String,proto3" json:"map_sint32_string,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapSint64String        map[int64]string                   `protobuf:"bytes,66,rep,name=map_sint64_string,json=mapSint64String,proto3" json:"map_sint64_string,omitempty" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapFixed32String       map[uint32]string                  `protobuf:"bytes,67,rep,name=map_fixed32_string,json=mapFixed32String,proto3" json:"map_fixed32_string,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapFixed64String       map[uint64]string                  `protobuf:"bytes,68,rep,name=map_fixed64_string,json=mapFixed64String,proto3" json:"map_fixed64_string,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapSfixed32String      map[int32]string                   `protobuf:"bytes,69,rep,name=map_sfixed32_string,json=mapSfixed32String,proto3" json:"map_sfixed32_string,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapSfixed64String      map[int64]string                   `protobuf:"bytes,70,rep,name=map_sfixed64_string,json=mapSfixed64String,proto3" json:"map_sfixed64_string,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapBoolString          map[bool]string                    `protobuf:"bytes,71,rep,name=map_bool_string,json=mapBoolString,proto3" json:"map_bool_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp              *timestamppb.Timestamp             `protobuf:"bytes,81,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration               *durationpb.Duration               `protobuf:"bytes,82,opt,name=duration,proto3" json:"duration,omitempty"`
	WrapperBool            *wrapperspb.BoolValue              `protobuf:"bytes,83,opt,name=wrapper_bool,json=wrapperBool,proto3" json:"wrapper_bool,omitempty"`
	WrapperBytes           *wrapperspb.BytesValue             `protobuf:"bytes,84,opt,name=wrapper_bytes,json=wrapperBytes,proto3" json:"wrapper_bytes,omitempty"`
	WrapperDouble          *wrapperspb.DoubleValue            `protobuf:"bytes,85,opt,name=wrapper_double,json=wrapperDouble,proto3" json:"wrapper_double,omitempty"`
	WrapperFloat           *wrapperspb.FloatValue             `protobuf:"bytes,86,opt,name=wrapper_float,json=wrapperFloat,proto3" json:"wrapper_float,omitempty"`
	WrapperInt32           *wrapperspb.Int32Value             `protobuf:"bytes,87,opt,name=wrapper_int32,json=wrapperInt32,proto3" json:"wrapper_int32,omitempty"`
	WrapperInt64           *wrapperspb.Int64Value             `protobuf:"bytes,88,opt,name=wrapper_int64,json=wrapperInt64,proto3" json:"wrapper_int64,omitempty"`
	WrapperString          *wrapperspb.StringValue            `protobuf:"bytes,89,opt,name=wrapper_string,json=wrapperString,proto3" json:"wrapper_string,omitempty"`
	WrapperUint32          *wrapperspb.UInt32Value            `protobuf:"bytes,90,opt,name=wrapper_uint32,json=wrapperUint32,proto3" json:"wrapper_uint32,omitempty"`
	WrapperUint64          *wrapperspb.UInt64Value            `protobuf:"bytes,91,opt,name=wrapper_uint64,json=wrapperUint64,proto3" json:"wrapper_uint64,omitempty"`
	ListTimestamp          []*timestamppb.Timestamp           `protobuf:"bytes,101,rep,name=list_timestamp,json=listTimestamp,proto3" json:"list_timestamp,omitempty"`
	ListDuration           []*durationpb.Duration             `protobuf:"bytes,102,rep,name=list_duration,json=listDuration,proto3" json:"list_duration,omitempty"`
	ListWrapperBool        []*wrapperspb.BoolValue            `protobuf:"bytes,103,rep,name=list_wrapper_bool,json=listWrapperBool,proto3" json:"list_wrapper_bool,omitempty"`
	ListWrapperBytes       []*wrapperspb.BytesValue           `protobuf:"bytes,104,rep,name=list_wrapper_bytes,json=listWrapperBytes,proto3" json:"list_wrapper_bytes,omitempty"`
	ListWrapperDouble      []*wrapperspb.DoubleValue          `protobuf:"bytes,105,rep,name=list_wrapper_double,json=listWrapperDouble,proto3" json:"list_wrapper_double,omitempty"`
	ListWrapperFloat       []*wrapperspb.FloatValue           `protobuf:"bytes,106,rep,name=list_wrapper_float,json=listWrapperFloat,proto3" json:"list_wrapper_float,omitempty"`
	ListWrapperInt32       []*wrapperspb.Int32Value           `protobuf:"bytes,107,rep,name=list_wrapper_int32,json=listWrapperInt32,proto3" json:"list_wrapper_int32,omitempty"`
	ListWrapperInt64       []*wrapperspb.Int64Value           `protobuf:"bytes,108,rep,name=list_wrapper_int64,json=listWrapperInt64,proto3" json:"list_wrapper_int64,omitempty"`
	ListWrapperString      []*wrapperspb.StringValue          `protobuf:"bytes,109,rep,name=list_wrapper_string,json=listWrapperString,proto3" json:"list_wrapper_string,omitempty"`
	ListWrapperUint32      []*wrapperspb.UInt32Value          `protobuf:"bytes,110,rep,name=list_wrapper_uint32,json=listWrapperUint32,proto3" json:"list_wrapper_uint32,omitempty"`
	ListWrapperUint64      []*wrapperspb.UInt64Value          `protobuf:"bytes,111,rep,name=list_wrapper_uint64,json=listWrapperUint64,proto3" json:"list_wrapper_uint64,omitempty"`
	MapStringTimestamp     map[string]*timestamppb.Timestamp  `protobuf:"bytes,121,rep,name=map_string_timestamp,json=mapStringTimestamp,proto3" json:"map_string_timestamp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringDuration      map[string]*durationpb.Duration    `protobuf:"bytes,122,rep,name=map_string_duration,json=mapStringDuration,proto3" json:"map_string_duration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperBool   map[string]*wrapperspb.BoolValue   `protobuf:"bytes,123,rep,name=map_string_wrapper_bool,json=mapStringWrapperBool,proto3" json:"map_string_wrapper_bool,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperBytes  map[string]*wrapperspb.BytesValue  `protobuf:"bytes,124,rep,name=map_string_wrapper_bytes,json=mapStringWrapperBytes,proto3" json:"map_string_wrapper_bytes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperDouble map[string]*wrapperspb.DoubleValue `protobuf:"bytes,125,rep,name=map_string_wrapper_double,json=mapStringWrapperDouble,proto3" json:"map_string_wrapper_double,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperFloat  map[string]*wrapperspb.FloatValue  `protobuf:"bytes,126,rep,name=map_string_wrapper_float,json=mapStringWrapperFloat,proto3" json:"map_string_wrapper_float,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperInt32  map[string]*wrapperspb.Int32Value  `protobuf:"bytes,127,rep,name=map_string_wrapper_int32,json=mapStringWrapperInt32,proto3" json:"map_string_wrapper_int32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperInt64  map[string]*wrapperspb.Int64Value  `protobuf:"bytes,128,rep,name=map_string_wrapper_int64,json=mapStringWrapperInt64,proto3" json:"map_string_wrapper_int64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperString map[string]*wrapperspb.StringValue `protobuf:"bytes,129,rep,name=map_string_wrapper_string,json=mapStringWrapperString,proto3" json:"map_string_wrapper_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperUint32 map[string]*wrapperspb.UInt32Value `protobuf:"bytes,130,rep,name=map_string_wrapper_uint32,json=mapStringWrapperUint32,proto3" json:"map_string_wrapper_uint32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringWrapperUint64 map[string]*wrapperspb.UInt64Value `protobuf:"bytes,131,rep,name=map_string_wrapper_uint64,json=mapStringWrapperUint64,proto3" json:"map_string_wrapper_uint64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Sound) Reset() {
	*x = Sound{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sound) ProtoMessage() {}

func (x *Sound) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sound.ProtoReflect.Descriptor instead.
func (*Sound) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Sound) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *Sound) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *Sound) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Sound) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Sound) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Sound) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Sound) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Sound) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Sound) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Sound) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Sound) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Sound) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Sound) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Sound) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *Sound) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Sound) GetNestedEnum() Sound_NestedEnum {
	if x != nil {
		return x.NestedEnum
	}
	return Sound_JAN
}

func (x *Sound) GetGlobalEnum() GlobalEnum {
	if x != nil {
		return x.GlobalEnum
	}
	return GlobalEnum_MON
}

func (x *Sound) GetNestedMsg() *Sound_NestedMessage {
	if x != nil {
		return x.NestedMsg
	}
	return nil
}

func (x *Sound) GetGlobalMsg() *GlobalMessage {
	if x != nil {
		return x.GlobalMsg
	}
	return nil
}

func (x *Sound) GetListDouble() []float64 {
	if x != nil {
		return x.ListDouble
	}
	return nil
}

func (x *Sound) GetListFloat() []float32 {
	if x != nil {
		return x.ListFloat
	}
	return nil
}

func (x *Sound) GetListInt32() []int32 {
	if x != nil {
		return x.ListInt32
	}
	return nil
}

func (x *Sound) GetListInt64() []int64 {
	if x != nil {
		return x.ListInt64
	}
	return nil
}

func (x *Sound) GetListUint32() []uint32 {
	if x != nil {
		return x.ListUint32
	}
	return nil
}

func (x *Sound) GetListUint64() []uint64 {
	if x != nil {
		return x.ListUint64
	}
	return nil
}

func (x *Sound) GetListSint32() []int32 {
	if x != nil {
		return x.ListSint32
	}
	return nil
}

func (x *Sound) GetListSint64() []int64 {
	if x != nil {
		return x.ListSint64
	}
	return nil
}

func (x *Sound) GetListFixed32() []uint32 {
	if x != nil {
		return x.ListFixed32
	}
	return nil
}

func (x *Sound) GetListFixed64() []uint64 {
	if x != nil {
		return x.ListFixed64
	}
	return nil
}

func (x *Sound) GetListSfixed32() []int32 {
	if x != nil {
		return x.ListSfixed32
	}
	return nil
}

func (x *Sound) GetListSfixed64() []int64 {
	if x != nil {
		return x.ListSfixed64
	}
	return nil
}

func (x *Sound) GetListBool() []bool {
	if x != nil {
		return x.ListBool
	}
	return nil
}

func (x *Sound) GetListString() []string {
	if x != nil {
		return x.ListString
	}
	return nil
}

func (x *Sound) GetListBytes() [][]byte {
	if x != nil {
		return x.ListBytes
	}
	return nil
}

func (x *Sound) GetListNestedEnum() []Sound_NestedEnum {
	if x != nil {
		return x.ListNestedEnum
	}
	return nil
}

func (x *Sound) GetListGlobalEnum() []GlobalEnum {
	if x != nil {
		return x.ListGlobalEnum
	}
	return nil
}

func (x *Sound) GetListNestedMsg() []*Sound_NestedMessage {
	if x != nil {
		return x.ListNestedMsg
	}
	return nil
}

func (x *Sound) GetListGlobalMsg() []*GlobalMessage {
	if x != nil {
		return x.ListGlobalMsg
	}
	return nil
}

func (x *Sound) GetMapStringDouble() map[string]float64 {
	if x != nil {
		return x.MapStringDouble
	}
	return nil
}

func (x *Sound) GetMapStringFloat() map[string]float32 {
	if x != nil {
		return x.MapStringFloat
	}
	return nil
}

func (x *Sound) GetMapStringInt32() map[string]int32 {
	if x != nil {
		return x.MapStringInt32
	}
	return nil
}

func (x *Sound) GetMapStringInt64() map[string]int64 {
	if x != nil {
		return x.MapStringInt64
	}
	return nil
}

func (x *Sound) GetMapStringUint32() map[string]uint32 {
	if x != nil {
		return x.MapStringUint32
	}
	return nil
}

func (x *Sound) GetMapStringUint64() map[string]uint64 {
	if x != nil {
		return x.MapStringUint64
	}
	return nil
}

func (x *Sound) GetMapStringSint32() map[string]int32 {
	if x != nil {
		return x.MapStringSint32
	}
	return nil
}

func (x *Sound) GetMapStringSint64() map[string]int64 {
	if x != nil {
		return x.MapStringSint64
	}
	return nil
}

func (x *Sound) GetMapStringFixed32() map[string]uint32 {
	if x != nil {
		return x.MapStringFixed32
	}
	return nil
}

func (x *Sound) GetMapStringFixed64() map[string]uint64 {
	if x != nil {
		return x.MapStringFixed64
	}
	return nil
}

func (x *Sound) GetMapStringSfixed32() map[string]int32 {
	if x != nil {
		return x.MapStringSfixed32
	}
	return nil
}

func (x *Sound) GetMapStringSfixed64() map[string]int64 {
	if x != nil {
		return x.MapStringSfixed64
	}
	return nil
}

func (x *Sound) GetMapStringBool() map[string]bool {
	if x != nil {
		return x.MapStringBool
	}
	return nil
}

func (x *Sound) GetMapStringString() map[string]string {
	if x != nil {
		return x.MapStringString
	}
	return nil
}

func (x *Sound) GetMapStringBytes() map[string][]byte {
	if x != nil {
		return x.MapStringBytes
	}
	return nil
}

func (x *Sound) GetMapStringNestedEnum() map[string]Sound_NestedEnum {
	if x != nil {
		return x.MapStringNestedEnum
	}
	return nil
}

func (x *Sound) GetMapStringGlobalEnum() map[string]GlobalEnum {
	if x != nil {
		return x.MapStringGlobalEnum
	}
	return nil
}

func (x *Sound) GetMapStringNestedMsg() map[string]*Sound_NestedMessage {
	if x != nil {
		return x.MapStringNestedMsg
	}
	return nil
}

func (x *Sound) GetMapStringGlobalMsg() map[string]*GlobalMessage {
	if x != nil {
		return x.MapStringGlobalMsg
	}
	return nil
}

func (x *Sound) GetMapInt32String() map[int32]string {
	if x != nil {
		return x.MapInt32String
	}
	return nil
}

func (x *Sound) GetMapInt64String() map[int64]string {
	if x != nil {
		return x.MapInt64String
	}
	return nil
}

func (x *Sound) GetMapUint32String() map[uint32]string {
	if x != nil {
		return x.MapUint32String
	}
	return nil
}

func (x *Sound) GetMapUint64String() map[uint64]string {
	if x != nil {
		return x.MapUint64String
	}
	return nil
}

func (x *Sound) GetMapSint32String() map[int32]string {
	if x != nil {
		return x.MapSint32String
	}
	return nil
}

func (x *Sound) GetMapSint64String() map[int64]string {
	if x != nil {
		return x.MapSint64String
	}
	return nil
}

func (x *Sound) GetMapFixed32String() map[uint32]string {
	if x != nil {
		return x.MapFixed32String
	}
	return nil
}

func (x *Sound) GetMapFixed64String() map[uint64]string {
	if x != nil {
		return x.MapFixed64String
	}
	return nil
}

func (x *Sound) GetMapSfixed32String() map[int32]string {
	if x != nil {
		return x.MapSfixed32String
	}
	return nil
}

func (x *Sound) GetMapSfixed64String() map[int64]string {
	if x != nil {
		return x.MapSfixed64String
	}
	return nil
}

func (x *Sound) GetMapBoolString() map[bool]string {
	if x != nil {
		return x.MapBoolString
	}
	return nil
}

func (x *Sound) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Sound) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Sound) GetWrapperBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.WrapperBool
	}
	return nil
}

func (x *Sound) GetWrapperBytes() *wrapperspb.BytesValue {
	if x != nil {
		return x.WrapperBytes
	}
	return nil
}

func (x *Sound) GetWrapperDouble() *wrapperspb.DoubleValue {
	if x != nil {
		return x.WrapperDouble
	}
	return nil
}

func (x *Sound) GetWrapperFloat() *wrapperspb.FloatValue {
	if x != nil {
		return x.WrapperFloat
	}
	return nil
}

func (x *Sound) GetWrapperInt32() *wrapperspb.Int32Value {
	if x != nil {
		return x.WrapperInt32
	}
	return nil
}

func (x *Sound) GetWrapperInt64() *wrapperspb.Int64Value {
	if x != nil {
		return x.WrapperInt64
	}
	return nil
}

func (x *Sound) GetWrapperString() *wrapperspb.StringValue {
	if x != nil {
		return x.WrapperString
	}
	return nil
}

func (x *Sound) GetWrapperUint32() *wrapperspb.UInt32Value {
	if x != nil {
		return x.WrapperUint32
	}
	return nil
}

func (x *Sound) GetWrapperUint64() *wrapperspb.UInt64Value {
	if x != nil {
		return x.WrapperUint64
	}
	return nil
}

func (x *Sound) GetListTimestamp() []*timestamppb.Timestamp {
	if x != nil {
		return x.ListTimestamp
	}
	return nil
}

func (x *Sound) GetListDuration() []*durationpb.Duration {
	if x != nil {
		return x.ListDuration
	}
	return nil
}

func (x *Sound) GetListWrapperBool() []*wrapperspb.BoolValue {
	if x != nil {
		return x.ListWrapperBool
	}
	return nil
}

func (x *Sound) GetListWrapperBytes() []*wrapperspb.BytesValue {
	if x != nil {
		return x.ListWrapperBytes
	}
	return nil
}

func (x *Sound) GetListWrapperDouble() []*wrapperspb.DoubleValue {
	if x != nil {
		return x.ListWrapperDouble
	}
	return nil
}

func (x *Sound) GetListWrapperFloat() []*wrapperspb.FloatValue {
	if x != nil {
		return x.ListWrapperFloat
	}
	return nil
}

func (x *Sound) GetListWrapperInt32() []*wrapperspb.Int32Value {
	if x != nil {
		return x.ListWrapperInt32
	}
	return nil
}

func (x *Sound) GetListWrapperInt64() []*wrapperspb.Int64Value {
	if x != nil {
		return x.ListWrapperInt64
	}
	return nil
}

func (x *Sound) GetListWrapperString() []*wrapperspb.StringValue {
	if x != nil {
		return x.ListWrapperString
	}
	return nil
}

func (x *Sound) GetListWrapperUint32() []*wrapperspb.UInt32Value {
	if x != nil {
		return x.ListWrapperUint32
	}
	return nil
}

func (x *Sound) GetListWrapperUint64() []*wrapperspb.UInt64Value {
	if x != nil {
		return x.ListWrapperUint64
	}
	return nil
}

func (x *Sound) GetMapStringTimestamp() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.MapStringTimestamp
	}
	return nil
}

func (x *Sound) GetMapStringDuration() map[string]*durationpb.Duration {
	if x != nil {
		return x.MapStringDuration
	}
	return nil
}

func (x *Sound) GetMapStringWrapperBool() map[string]*wrapperspb.BoolValue {
	if x != nil {
		return x.MapStringWrapperBool
	}
	return nil
}

func (x *Sound) GetMapStringWrapperBytes() map[string]*wrapperspb.BytesValue {
	if x != nil {
		return x.MapStringWrapperBytes
	}
	return nil
}

func (x *Sound) GetMapStringWrapperDouble() map[string]*wrapperspb.DoubleValue {
	if x != nil {
		return x.MapStringWrapperDouble
	}
	return nil
}

func (x *Sound) GetMapStringWrapperFloat() map[string]*wrapperspb.FloatValue {
	if x != nil {
		return x.MapStringWrapperFloat
	}
	return nil
}

func (x *Sound) GetMapStringWrapperInt32() map[string]*wrapperspb.Int32Value {
	if x != nil {
		return x.MapStringWrapperInt32
	}
	return nil
}

func (x *Sound) GetMapStringWrapperInt64() map[string]*wrapperspb.Int64Value {
	if x != nil {
		return x.MapStringWrapperInt64
	}
	return nil
}

func (x *Sound) GetMapStringWrapperString() map[string]*wrapperspb.StringValue {
	if x != nil {
		return x.MapStringWrapperString
	}
	return nil
}

func (x *Sound) GetMapStringWrapperUint32() map[string]*wrapperspb.UInt32Value {
	if x != nil {
		return x.MapStringWrapperUint32
	}
	return nil
}

func (x *Sound) GetMapStringWrapperUint64() map[string]*wrapperspb.UInt64Value {
	if x != nil {
		return x.MapStringWrapperUint64
	}
	return nil
}

type GlobalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalMessage) Reset() {
	*x = GlobalMessage{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalMessage) ProtoMessage() {}

func (x *GlobalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalMessage.ProtoReflect.Descriptor instead.
func (*GlobalMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Sound_NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sound_NestedMessage) Reset() {
	*x = Sound_NestedMessage{}
	mi := &file_types_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sound_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sound_NestedMessage) ProtoMessage() {}

func (x *Sound_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sound_NestedMessage.ProtoReflect.Descriptor instead.
func (*Sound_NestedMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0, 41}
}

func (x *Sound_NestedMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\aexample\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe4L\n" +
	"\x05Sound\x12\x16\n" +
	"\x06double\x18\x01 \x01(\x01R\x06double\x12\x14\n" +
	"\x05float\x18\x02 \x01(\x02R\x05float\x12\x14\n" +
	"\x05int32\x18\x03 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x04 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\x05 \x01(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\x06 \x01(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\a \x01(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\b \x01(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\t \x01(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\n" +
	" \x01(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\v \x01(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\f \x01(\x10R\bsfixed64\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\fR\x05bytes\x12:\n" +
	"\vnested_enum\x18\x10 \x01(\x0e2\x19.example.Sound.NestedEnumR\n" +
	"nestedEnum\x124\n" +
	"\vglobal_enum\x18\x11 \x01(\x0e2\x13.example.GlobalEnumR\n" +
	"globalEnum\x12;\n" +
	"\n" +
	"nested_msg\x18\x12 \x01(\v2\x1c.example.Sound.NestedMessageR\tnestedMsg\x125\n" +
	"\n" +
	"global_msg\x18\x13 \x01(\v2\x16.example.GlobalMessageR\tglobalMsg\x12\x1f\n" +
	"\vlist_double\x18\x15 \x03(\x01R\n" +
	"listDouble\x12\x1d\n" +
	"\n" +
	"list_float\x18\x16 \x03(\x02R\tlistFloat\x12\x1d\n" +
	"\n" +
	"list_int32\x18\x17 \x03(\x05R\tlistInt32\x12\x1d\n" +
	"\n" +
	"list_int64\x18\x18 \x03(\x03R\tlistInt64\x12\x1f\n" +
	"\vlist_uint32\x18\x19 \x03(\rR\n" +
	"listUint32\x12\x1f\n" +
	"\vlist_uint64\x18\x1a \x03(\x04R\n" +
	"listUint64\x12\x1f\n" +
	"\vlist_sint32\x18\x1b \x03(\x11R\n" +
	"listSint32\x12\x1f\n" +
	"\vlist_sint64\x18\x1c \x03(\x12R\n" +
	"listSint64\x12!\n" +
	"\flist_fixed32\x18\x1d \x03(\aR\vlistFixed32\x12!\n" +
	"\flist_fixed64\x18\x1e \x03(\x06R\vlistFixed64\x12#\n" +
	"\rlist_sfixed32\x18\x1f \x03(\x0fR\flistSfixed32\x12#\n" +
	"\rlist_sfixed64\x18  \x03(\x10R\flistSfixed64\x12\x1b\n" +
	"\tlist_bool\x18! \x03(\bR\blistBool\x12\x1f\n" +
	"\vlist_string\x18\" \x03(\tR\n" +
	"listString\x12\x1d\n" +
	"\n" +
	"list_bytes\x18# \x03(\fR\tlistBytes\x12C\n" +
	"\x10list_nested_enum\x18$ \x03(\x0e2\x19.example.Sound.NestedEnumR\x0elistNestedEnum\x12=\n" +
	"\x10list_global_enum\x18% \x03(\x0e2\x13.example.GlobalEnumR\x0elistGlobalEnum\x12D\n" +
	"\x0flist_nested_msg\x18& \x03(\v2\x1c.example.Sound.NestedMessageR\rlistNestedMsg\x12>\n" +
	"\x0flist_global_msg\x18' \x03(\v2\x16.example.GlobalMessageR\rlistGlobalMsg\x12O\n" +
	"\x11map_string_double\x18) \x03(\v2#.example.Sound.MapStringDoubleEntryR\x0fmapStringDouble\x12L\n" +
	"\x10map_string_float\x18* \x03(\v2\".example.Sound.MapStringFloatEntryR\x0emapStringFloat\x12L\n" +
	"\x10map_string_int32\x18+ \x03(\v2\".example.Sound.MapStringInt32EntryR\x0emapStringInt32\x12L\n" +
	"\x10map_string_int64\x18, \x03(\v2\".example.Sound.MapStringInt64EntryR\x0emapStringInt64\x12O\n" +
	"\x11map_string_uint32\x18- \x03(\v2#.example.Sound.MapStringUint32EntryR\x0fmapStringUint32\x12O\n" +
	"\x11map_string_uint64\x18. \x03(\v2#.example.Sound.MapStringUint64EntryR\x0fmapStringUint64\x12O\n" +
	"\x11map_string_sint32\x18/ \x03(\v2#.example.Sound.MapStringSint32EntryR\x0fmapStringSint32\x12O\n" +
	"\x11map_string_sint64\x180 \x03(\v2#.example.Sound.MapStringSint64EntryR\x0fmapStringSint64\x12R\n" +
	"\x12map_string_fixed32\x181 \x03(\v2$.example.Sound.MapStringFixed32EntryR\x10mapStringFixed32\x12R\n" +
	"\x12map_string_fixed64\x182 \x03(\v2$.example.Sound.MapStringFixed64EntryR\x10mapStringFixed64\x12U\n" +
	"\x13map_string_sfixed32\x183 \x03(\v2%.example.Sound.MapStringSfixed32EntryR\x11mapStringSfixed32\x12U\n" +
	"\x13map_string_sfixed64\x184 \x03(\v2%.example.Sound.MapStringSfixed64EntryR\x11mapStringSfixed64\x12I\n" +
	"\x0fmap_string_bool\x185 \x03(\v2!.example.Sound.MapStringBoolEntryR\rmapStringBool\x12O\n" +
	"\x11map_string_string\x186 \x03(\v2#.example.Sound.MapStringStringEntryR\x0fmapStringString\x12L\n" +
	"\x10map_string_bytes\x187 \x03(\v2\".example.Sound.MapStringBytesEntryR\x0emapStringBytes\x12\\\n" +
	"\x16map_string_nested_enum\x188 \x03(\v2'.example.Sound.MapStringNestedEnumEntryR\x13mapStringNestedEnum\x12\\\n" +
	"\x16map_string_global_enum\x189 \x03(\v2'.example.Sound.MapStringGlobalEnumEntryR\x13mapStringGlobalEnum\x12Y\n" +
	"\x15map_string_nested_msg\x18: \x03(\v2&.example.Sound.MapStringNestedMsgEntryR\x12mapStringNestedMsg\x12Y\n" +
	"\x15map_string_global_msg\x18; \x03(\v2&.example.Sound.MapStringGlobalMsgEntryR\x12mapStringGlobalMsg\x12L\n" +
	"\x10map_int32_string\x18= \x03(\v2\".example.Sound.MapInt32StringEntryR\x0emapInt32String\x12L\n" +
	"\x10map_int64_string\x18> \x03(\v2\".example.Sound.MapInt64StringEntryR\x0emapInt64String\x12O\n" +
	"\x11map_uint32_string\x18? \x03(\v2#.example.Sound.MapUint32StringEntryR\x0fmapUint32String\x12O\n" +
	"\x11map_uint64_string\x18@ \x03(\v2#.example.Sound.MapUint64StringEntryR\x0fmapUint64String\x12O\n" +
	"\x11map_sint32_string\x18A \x03(\v2#.example.Sound.MapSint32StringEntryR\x0fmapSint32String\x12O\n" +
	"\x11map_sint64_string\x18B \x03(\v2#.example.Sound.MapSint64StringEntryR\x0fmapSint64String\x12R\n" +
	"\x12map_fixed32_string\x18C \x03(\v2$.example.Sound.MapFixed32StringEntryR\x10mapFixed32String\x12R\n" +
	"\x12map_fixed64_string\x18D \x03(\v2$.example.Sound.MapFixed64StringEntryR\x10mapFixed64String\x12U\n" +
	"\x13map_sfixed32_string\x18E \x03(\v2%.example.Sound.MapSfixed32StringEntryR\x11mapSfixed32String\x12U\n" +
	"\x13map_sfixed64_string\x18F \x03(\v2%.example.Sound.MapSfixed64StringEntryR\x11mapSfixed64String\x12I\n" +
	"\x0fmap_bool_string\x18G \x03(\v2!.example.Sound.MapBoolStringEntryR\rmapBoolString\x128\n" +
	"\ttimestamp\x18Q \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\bduration\x18R \x01(\v2\x19.google.protobuf.DurationR\bduration\x12=\n" +
	"\fwrapper_bool\x18S \x01(\v2\x1a.google.protobuf.BoolValueR\vwrapperBool\x12@\n" +
	"\rwrapper_bytes\x18T \x01(\v2\x1b.google.protobuf.BytesValueR\fwrapperBytes\x12C\n" +
	"\x0ewrapper_double\x18U \x01(\v2\x1c.google.protobuf.DoubleValueR\rwrapperDouble\x12@\n" +
	"\rwrapper_float\x18V \x01(\v2\x1b.google.protobuf.FloatValueR\fwrapperFloat\x12@\n" +
	"\rwrapper_int32\x18W \x01(\v2\x1b.google.protobuf.Int32ValueR\fwrapperInt32\x12@\n" +
	"\rwrapper_int64\x18X \x01(\v2\x1b.google.protobuf.Int64ValueR\fwrapperInt64\x12C\n" +
	"\x0ewrapper_string\x18Y \x01(\v2\x1c.google.protobuf.StringValueR\rwrapperString\x12C\n" +
	"\x0ewrapper_uint32\x18Z \x01(\v2\x1c.google.protobuf.UInt32ValueR\rwrapperUint32\x12C\n" +
	"\x0ewrapper_uint64\x18[ \x01(\v2\x1c.google.protobuf.UInt64ValueR\rwrapperUint64\x12A\n" +
	"\x0elist_timestamp\x18e \x03(\v2\x1a.google.protobuf.TimestampR\rlistTimestamp\x12>\n" +
	"\rlist_duration\x18f \x03(\v2\x19.google.protobuf.DurationR\flistDuration\x12F\n" +
	"\x11list_wrapper_bool\x18g \x03(\v2\x1a.google.protobuf.BoolValueR\x0flistWrapperBool\x12I\n" +
	"\x12list_wrapper_bytes\x18h \x03(\v2\x1b.google.protobuf.BytesValueR\x10listWrapperBytes\x12L\n" +
	"\x13list_wrapper_double\x18i \x03(\v2\x1c.google.protobuf.DoubleValueR\x11listWrapperDouble\x12I\n" +
	"\x12list_wrapper_float\x18j \x03(\v2\x1b.google.protobuf.FloatValueR\x10listWrapperFloat\x12I\n" +
	"\x12list_wrapper_int32\x18k \x03(\v2\x1b.google.protobuf.Int32ValueR\x10listWrapperInt32\x12I\n" +
	"\x12list_wrapper_int64\x18l \x03(\v2\x1b.google.protobuf.Int64ValueR\x10listWrapperInt64\x12L\n" +
	"\x13list_wrapper_string\x18m \x03(\v2\x1c.google.protobuf.StringValueR\x11listWrapperString\x12L\n" +
	"\x13list_wrapper_uint32\x18n \x03(\v2\x1c.google.protobuf.UInt32ValueR\x11listWrapperUint32\x12L\n" +
	"\x13list_wrapper_uint64\x18o \x03(\v2\x1c.google.protobuf.UInt64ValueR\x11listWrapperUint64\x12X\n" +
	"\x14map_string_timestamp\x18y \x03(\v2&.example.Sound.MapStringTimestampEntryR\x12mapStringTimestamp\x12U\n" +
	"\x13map_string_duration\x18z \x03(\v2%.example.Sound.MapStringDurationEntryR\x11mapStringDuration\x12_\n" +
	"\x17map_string_wrapper_bool\x18{ \x03(\v2(.example.Sound.MapStringWrapperBoolEntryR\x14mapStringWrapperBool\x12b\n" +
	"\x18map_string_wrapper_bytes\x18| \x03(\v2).example.Sound.MapStringWrapperBytesEntryR\x15mapStringWrapperBytes\x12e\n" +
	"\x19map_string_wrapper_double\x18} \x03(\v2*.example.Sound.MapStringWrapperDoubleEntryR\x16mapStringWrapperDouble\x12b\n" +
	"\x18map_string_wrapper_float\x18~ \x03(\v2).example.Sound.MapStringWrapperFloatEntryR\x15mapStringWrapperFloat\x12b\n" +
	"\x18map_string_wrapper_int32\x18\x7f \x03(\v2).example.Sound.MapStringWrapperInt32EntryR\x15mapStringWrapperInt32\x12c\n" +
	"\x18map_string_wrapper_int64\x18\x80\x01 \x03(\v2).example.Sound.MapStringWrapperInt64EntryR\x15mapStringWrapperInt64\x12f\n" +
	"\x19map_string_wrapper_string\x18\x81\x01 \x03(\v2*.example.Sound.MapStringWrapperStringEntryR\x16mapStringWrapperString\x12f\n" +
	"\x19map_string_wrapper_uint32\x18\x82\x01 \x03(\v2*.example.Sound.MapStringWrapperUint32EntryR\x16mapStringWrapperUint32\x12f\n" +
	"\x19map_string_wrapper_uint64\x18\x83\x01 \x03(\v2*.example.Sound.MapStringWrapperUint64EntryR\x16mapStringWrapperUint64\x1aB\n" +
	"\x14MapStringDoubleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aA\n" +
	"\x13MapStringFloatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aA\n" +
	"\x13MapStringInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aA\n" +
	"\x13MapStringInt64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14MapStringUint32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aB\n" +
	"\x14MapStringUint64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aB\n" +
	"\x14MapStringSint32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x11R\x05value:\x028\x01\x1aB\n" +
	"\x14MapStringSint64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x12R\x05value:\x028\x01\x1aC\n" +
	"\x15MapStringFixed32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\aR\x05value:\x028\x01\x1aC\n" +
	"\x15MapStringFixed64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x06R\x05value:\x028\x01\x1aD\n" +
	"\x16MapStringSfixed32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x0fR\x05value:\x028\x01\x1aD\n" +
	"\x16MapStringSfixed64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x10R\x05value:\x028\x01\x1a@\n" +
	"\x12MapStringBoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aB\n" +
	"\x14MapStringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13MapStringBytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aa\n" +
	"\x18MapStringNestedEnumEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\x0e2\x19.example.Sound.NestedEnumR\x05value:\x028\x01\x1a[\n" +
	"\x18MapStringGlobalEnumEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\x0e2\x13.example.GlobalEnumR\x05value:\x028\x01\x1ac\n" +
	"\x17MapStringNestedMsgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.example.Sound.NestedMessageR\x05value:\x028\x01\x1a]\n" +
	"\x17MapStringGlobalMsgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.example.GlobalMessageR\x05value:\x028\x01\x1aA\n" +
	"\x13MapInt32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13MapInt64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14MapUint32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14MapUint64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14MapSint32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14MapSint64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15MapFixed32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\aR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15MapFixed64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x06R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16MapSfixed32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x0fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16MapSfixed64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x10R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12MapBoolStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aa\n" +
	"\x17MapStringTimestampEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1a_\n" +
	"\x16MapStringDurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\x1ac\n" +
	"\x19MapStringWrapperBoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x05value:\x028\x01\x1ae\n" +
	"\x1aMapStringWrapperBytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.BytesValueR\x05value:\x028\x01\x1ag\n" +
	"\x1bMapStringWrapperDoubleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.DoubleValueR\x05value:\x028\x01\x1ae\n" +
	"\x1aMapStringWrapperFloatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.FloatValueR\x05value:\x028\x01\x1ae\n" +
	"\x1aMapStringWrapperInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05value:\x028\x01\x1ae\n" +
	"\x1aMapStringWrapperInt64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05value:\x028\x01\x1ag\n" +
	"\x1bMapStringWrapperStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value:\x028\x01\x1ag\n" +
	"\x1bMapStringWrapperUint32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x05value:\x028\x01\x1ag\n" +
	"\x1bMapStringWrapperUint64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x05value:\x028\x01\x1a%\n" +
	"\rNestedMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"'\n" +
	"\n" +
	"NestedEnum\x12\a\n" +
	"\x03JAN\x10\x00\x12\a\n" +
	"\x03FEB\x10\x01\x12\a\n" +
	"\x03MAR\x10\x02\"%\n" +
	"\rGlobalMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*'\n" +
	"\n" +
	"GlobalEnum\x12\a\n" +
	"\x03MON\x10\x00\x12\a\n" +
	"\x03TUE\x10\x01\x12\a\n" +
	"\x03WED\x10\x022/\n" +
	"\x05Types\x12&\n" +
	"\x04Echo\x12\x0e.example.Sound\x1a\x0e.example.SoundB\x06Z\x04.;pbb\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_types_proto_goTypes = []any{
	(GlobalEnum)(0),                // 0: example.GlobalEnum
	(Sound_NestedEnum)(0),          // 1: example.Sound.NestedEnum
	(*Sound)(nil),                  // 2: example.Sound
	(*GlobalMessage)(nil),          // 3: example.GlobalMessage
	nil,                            // 4: example.Sound.MapStringDoubleEntry
	nil,                            // 5: example.Sound.MapStringFloatEntry
	nil,                            // 6: example.Sound.MapStringInt32Entry
	nil,                            // 7: example.Sound.MapStringInt64Entry
	nil,                            // 8: example.Sound.MapStringUint32Entry
	nil,                            // 9: example.Sound.MapStringUint64Entry
	nil,                            // 10: example.Sound.MapStringSint32Entry
	nil,                            // 11: example.Sound.MapStringSint64Entry
	nil,                            // 12: example.Sound.MapStringFixed32Entry
	nil,                            // 13: example.Sound.MapStringFixed64Entry
	nil,                            // 14: example.Sound.MapStringSfixed32Entry
	nil,                            // 15: example.Sound.MapStringSfixed64Entry
	nil,                            // 16: example.Sound.MapStringBoolEntry
	nil,                            // 17: example.Sound.MapStringStringEntry
	nil,                            // 18: example.Sound.MapStringBytesEntry
	nil,                            // 19: example.Sound.MapStringNestedEnumEntry
	nil,                            // 20: example.Sound.MapStringGlobalEnumEntry
	nil,                            // 21: example.Sound.MapStringNestedMsgEntry
	nil,                            // 22: example.Sound.MapStringGlobalMsgEntry
	nil,                            // 23: example.Sound.MapInt32StringEntry
	nil,                            // 24: example.Sound.MapInt64StringEntry
	nil,                            // 25: example.Sound.MapUint32StringEntry
	nil,                            // 26: example.Sound.MapUint64StringEntry
	nil,                            // 27: example.Sound.MapSint32StringEntry
	nil,                            // 28: example.Sound.MapSint64StringEntry
	nil,                            // 29: example.Sound.MapFixed32StringEntry
	nil,                            // 30: example.Sound.MapFixed64StringEntry
	nil,                            // 31: example.Sound.MapSfixed32StringEntry
	nil,                            // 32: example.Sound.MapSfixed64StringEntry
	nil,                            // 33: example.Sound.MapBoolStringEntry
	nil,                            // 34: example.Sound.MapStringTimestampEntry
	nil,                            // 35: example.Sound.MapStringDurationEntry
	nil,                            // 36: example.Sound.MapStringWrapperBoolEntry
	nil,                            // 37: example.Sound.MapStringWrapperBytesEntry
	nil,                            // 38: example.Sound.MapStringWrapperDoubleEntry
	nil,                            // 39: example.Sound.MapStringWrapperFloatEntry
	nil,                            // 40: example.Sound.MapStringWrapperInt32Entry
	nil,                            // 41: example.Sound.MapStringWrapperInt64Entry
	nil,                            // 42: example.Sound.MapStringWrapperStringEntry
	nil,                            // 43: example.Sound.MapStringWrapperUint32Entry
	nil,                            // 44: example.Sound.MapStringWrapperUint64Entry
	(*Sound_NestedMessage)(nil),    // 45: example.Sound.NestedMessage
	(*timestamppb.Timestamp)(nil),  // 46: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 47: google.protobuf.Duration
	(*wrapperspb.BoolValue)(nil),   // 48: google.protobuf.BoolValue
	(*wrapperspb.BytesValue)(nil),  // 49: google.protobuf.BytesValue
	(*wrapperspb.DoubleValue)(nil), // 50: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 51: google.protobuf.FloatValue
	(*wrapperspb.Int32Value)(nil),  // 52: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 53: google.protobuf.Int64Value
	(*wrapperspb.StringValue)(nil), // 54: google.protobuf.StringValue
	(*wrapperspb.UInt32Value)(nil), // 55: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 56: google.protobuf.UInt64Value
}
var file_types_proto_depIdxs = []int32{
	1,  // 0: example.Sound.nested_enum:type_name -> example.Sound.NestedEnum
	0,  // 1: example.Sound.global_enum:type_name -> example.GlobalEnum
	45, // 2: example.Sound.nested_msg:type_name -> example.Sound.NestedMessage
	3,  // 3: example.Sound.global_msg:type_name -> example.GlobalMessage
	1,  // 4: example.Sound.list_nested_enum:type_name -> example.Sound.NestedEnum
	0,  // 5: example.Sound.list_global_enum:type_name -> example.GlobalEnum
	45, // 6: example.Sound.list_nested_msg:type_name -> example.Sound.NestedMessage
	3,  // 7: example.Sound.list_global_msg:type_name -> example.GlobalMessage
	4,  // 8: example.Sound.map_string_double:type_name -> example.Sound.MapStringDoubleEntry
	5,  // 9: example.Sound.map_string_float:type_name -> example.Sound.MapStringFloatEntry
	6,  // 10: example.Sound.map_string_int32:type_name -> example.Sound.MapStringInt32Entry
	7,  // 11: example.Sound.map_string_int64:type_name -> example.Sound.MapStringInt64Entry
	8,  // 12: example.Sound.map_string_uint32:type_name -> example.Sound.MapStringUint32Entry
	9,  // 13: example.Sound.map_string_uint64:type_name -> example.Sound.MapStringUint64Entry
	10, // 14: example.Sound.map_string_sint32:type_name -> example.Sound.MapStringSint32Entry
	11, // 15: example.Sound.map_string_sint64:type_name -> example.Sound.MapStringSint64Entry
	12, // 16: example.Sound.map_string_fixed32:type_name -> example.Sound.MapStringFixed32Entry
	13, // 17: example.Sound.map_string_fixed64:type_name -> example.Sound.MapStringFixed64Entry
	14, // 18: example.Sound.map_string_sfixed32:type_name -> example.Sound.MapStringSfixed32Entry
	15, // 19: example.Sound.map_string_sfixed64:type_name -> example.Sound.MapStringSfixed64Entry
	16, // 20: example.Sound.map_string_bool:type_name -> example.Sound.MapStringBoolEntry
	17, // 21: example.Sound.map_string_string:type_name -> example.Sound.MapStringStringEntry
	18, // 22: example.Sound.map_string_bytes:type_name -> example.Sound.MapStringBytesEntry
	19, // 23: example.Sound.map_string_nested_enum:type_name -> example.Sound.MapStringNestedEnumEntry
	20, // 24: example.Sound.map_string_global_enum:type_name -> example.Sound.MapStringGlobalEnumEntry
	21, // 25: example.Sound.map_string_nested_msg:type_name -> example.Sound.MapStringNestedMsgEntry
	22, // 26: example.Sound.map_string_global_msg:type_name -> example.Sound.MapStringGlobalMsgEntry
	23, // 27: example.Sound.map_int32_string:type_name -> example.Sound.MapInt32StringEntry
	24, // 28: example.Sound.map_int64_string:type_name -> example.Sound.MapInt64StringEntry
	25, // 29: example.Sound.map_uint32_string:type_name -> example.Sound.MapUint32StringEntry
	26, // 30: example.Sound.map_uint64_string:type_name -> example.Sound.MapUint64StringEntry
	27, // 31: example.Sound.map_sint32_string:type_name -> example.Sound.MapSint32StringEntry
	28, // 32: example.Sound.map_sint64_string:type_name -> example.Sound.MapSint64StringEntry
	29, // 33: example.Sound.map_fixed32_string:type_name -> example.Sound.MapFixed32StringEntry
	30, // 34: example.Sound.map_fixed64_string:type_name -> example.Sound.MapFixed64StringEntry
	31, // 35: example.Sound.map_sfixed32_string:type_name -> example.Sound.MapSfixed32StringEntry
	32, // 36: example.Sound.map_sfixed64_string:type_name -> example.Sound.MapSfixed64StringEntry
	33, // 37: example.Sound.map_bool_string:type_name -> example.Sound.MapBoolStringEntry
	46, // 38: example.Sound.timestamp:type_name -> google.protobuf.Timestamp
	47, // 39: example.Sound.duration:type_name -> google.protobuf.Duration
	48, // 40: example.Sound.wrapper_bool:type_name -> google.protobuf.BoolValue
	49, // 41: example.Sound.wrapper_bytes:type_name -> google.protobuf.BytesValue
	50, // 42: example.Sound.wrapper_double:type_name -> google.protobuf.DoubleValue
	51, // 43: example.Sound.wrapper_float:type_name -> google.protobuf.FloatValue
	52, // 44: example.Sound.wrapper_int32:type_name -> google.protobuf.Int32Value
	53, // 45: example.Sound.wrapper_int64:type_name -> google.protobuf.Int64Value
	54, // 46: example.Sound.wrapper_string:type_name -> google.protobuf.StringValue
	55, // 47: example.Sound.wrapper_uint32:type_name -> google.protobuf.UInt32Value
	56, // 48: example.Sound.wrapper_uint64:type_name -> google.protobuf.UInt64Value
	46, // 49: example.Sound.list_timestamp:type_name -> google.protobuf.Timestamp
	47, // 50: example.Sound.list_duration:type_name -> google.protobuf.Duration
	48, // 51: example.Sound.list_wrapper_bool:type_name -> google.protobuf.BoolValue
	49, // 52: example.Sound.list_wrapper_bytes:type_name -> google.protobuf.BytesValue
	50, // 53: example.Sound.list_wrapper_double:type_name -> google.protobuf.DoubleValue
	51, // 54: example.Sound.list_wrapper_float:type_name -> google.protobuf.FloatValue
	52, // 55: example.Sound.list_wrapper_int32:type_name -> google.protobuf.Int32Value
	53, // 56: example.Sound.list_wrapper_int64:type_name -> google.protobuf.Int64Value
	54, // 57: example.Sound.list_wrapper_string:type_name -> google.protobuf.StringValue
	55, // 58: example.Sound.list_wrapper_uint32:type_name -> google.protobuf.UInt32Value
	56, // 59: example.Sound.list_wrapper_uint64:type_name -> google.protobuf.UInt64Value
	34, // 60: example.Sound.map_string_timestamp:type_name -> example.Sound.MapStringTimestampEntry
	35, // 61: example.Sound.map_string_duration:type_name -> example.Sound.MapStringDurationEntry
	36, // 62: example.Sound.map_string_wrapper_bool:type_name -> example.Sound.MapStringWrapperBoolEntry
	37, // 63: example.Sound.map_string_wrapper_bytes:type_name -> example.Sound.MapStringWrapperBytesEntry
	38, // 64: example.Sound.map_string_wrapper_double:type_name -> example.Sound.MapStringWrapperDoubleEntry
	39, // 65: example.Sound.map_string_wrapper_float:type_name -> example.Sound.MapStringWrapperFloatEntry
	40, // 66: example.Sound.map_string_wrapper_int32:type_name -> example.Sound.MapStringWrapperInt32Entry
	41, // 67: example.Sound.map_string_wrapper_int64:type_name -> example.Sound.MapStringWrapperInt64Entry
	42, // 68: example.Sound.map_string_wrapper_string:type_name -> example.Sound.MapStringWrapperStringEntry
	43, // 69: example.Sound.map_string_wrapper_uint32:type_name -> example.Sound.MapStringWrapperUint32Entry
	44, // 70: example.Sound.map_string_wrapper_uint64:type_name -> example.Sound.MapStringWrapperUint64Entry
	1,  // 71: example.Sound.MapStringNestedEnumEntry.value:type_name -> example.Sound.NestedEnum
	0,  // 72: example.Sound.MapStringGlobalEnumEntry.value:type_name -> example.GlobalEnum
	45, // 73: example.Sound.MapStringNestedMsgEntry.value:type_name -> example.Sound.NestedMessage
	3,  // 74: example.Sound.MapStringGlobalMsgEntry.value:type_name -> example.GlobalMessage
	46, // 75: example.Sound.MapStringTimestampEntry.value:type_name -> google.protobuf.Timestamp
	47, // 76: example.Sound.MapStringDurationEntry.value:type_name -> google.protobuf.Duration
	48, // 77: example.Sound.MapStringWrapperBoolEntry.value:type_name -> google.protobuf.BoolValue
	49, // 78: example.Sound.MapStringWrapperBytesEntry.value:type_name -> google.protobuf.BytesValue
	50, // 79: example.Sound.MapStringWrapperDoubleEntry.value:type_name -> google.protobuf.DoubleValue
	51, // 80: example.Sound.MapStringWrapperFloatEntry.value:type_name -> google.protobuf.FloatValue
	52, // 81: example.Sound.MapStringWrapperInt32Entry.value:type_name -> google.protobuf.Int32Value
	53, // 82: example.Sound.MapStringWrapperInt64Entry.value:type_name -> google.protobuf.Int64Value
	54, // 83: example.Sound.MapStringWrapperStringEntry.value:type_name -> google.protobuf.StringValue
	55, // 84: example.Sound.MapStringWrapperUint32Entry.value:type_name -> google.protobuf.UInt32Value
	56, // 85: example.Sound.MapStringWrapperUint64Entry.value:type_name -> google.protobuf.UInt64Value
	2,  // 86: example.Types.Echo:input_type -> example.Sound
	2,  // 87: example.Types.Echo:output_type -> example.Sound
	87, // [87:88] is the sub-list for method output_type
	86, // [86:87] is the sub-list for method input_type
	86, // [86:86] is the sub-list for extension type_name
	86, // [86:86] is the sub-list for extension extendee
	0,  // [0:86] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
