// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/bank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositRequest struct {
	state                 protoimpl.MessageState                  `protogen:"open.v1"`
	Parent                string                                  `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Tenant                string                                  `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Environment           string                                  `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Clusters              []*DepositRequest_ClusterWithNamespaces `protobuf:"bytes,4,rep,name=clusters,proto3" json:"clusters,omitempty"`
	ClusterWithNamespaces *DepositRequest_ClusterWithNamespaces   `protobuf:"bytes,5,opt,name=cluster_with_namespaces,json=clusterWithNamespaces,proto3" json:"cluster_with_namespaces,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_pb_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{0}
}

func (x *DepositRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DepositRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *DepositRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *DepositRequest) GetClusters() []*DepositRequest_ClusterWithNamespaces {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *DepositRequest) GetClusterWithNamespaces() *DepositRequest_ClusterWithNamespaces {
	if x != nil {
		return x.ClusterWithNamespaces
	}
	return nil
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_pb_bank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{1}
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_pb_bank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{2}
}

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_pb_bank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{3}
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_pb_bank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{4}
}

type DepositReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReply) Reset() {
	*x = DepositReply{}
	mi := &file_pb_bank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReply) ProtoMessage() {}

func (x *DepositReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReply.ProtoReflect.Descriptor instead.
func (*DepositReply) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{5}
}

func (x *DepositReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DepositRequest_ClusterWithNamespaces struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Cluster       *Cluster                                   `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespaces    []*DepositRequest_NamespaceWithDeployments `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest_ClusterWithNamespaces) Reset() {
	*x = DepositRequest_ClusterWithNamespaces{}
	mi := &file_pb_bank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest_ClusterWithNamespaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest_ClusterWithNamespaces) ProtoMessage() {}

func (x *DepositRequest_ClusterWithNamespaces) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest_ClusterWithNamespaces.ProtoReflect.Descriptor instead.
func (*DepositRequest_ClusterWithNamespaces) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DepositRequest_ClusterWithNamespaces) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *DepositRequest_ClusterWithNamespaces) GetNamespaces() []*DepositRequest_NamespaceWithDeployments {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type DepositRequest_NamespaceWithDeployments struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Namespace     *Namespace                                `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Deployments   []*DepositRequest_DeploymentWithEndpoints `protobuf:"bytes,2,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest_NamespaceWithDeployments) Reset() {
	*x = DepositRequest_NamespaceWithDeployments{}
	mi := &file_pb_bank_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest_NamespaceWithDeployments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest_NamespaceWithDeployments) ProtoMessage() {}

func (x *DepositRequest_NamespaceWithDeployments) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest_NamespaceWithDeployments.ProtoReflect.Descriptor instead.
func (*DepositRequest_NamespaceWithDeployments) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DepositRequest_NamespaceWithDeployments) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *DepositRequest_NamespaceWithDeployments) GetDeployments() []*DepositRequest_DeploymentWithEndpoints {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type DepositRequest_DeploymentWithEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest_DeploymentWithEndpoints) Reset() {
	*x = DepositRequest_DeploymentWithEndpoints{}
	mi := &file_pb_bank_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest_DeploymentWithEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest_DeploymentWithEndpoints) ProtoMessage() {}

func (x *DepositRequest_DeploymentWithEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bank_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest_DeploymentWithEndpoints.ProtoReflect.Descriptor instead.
func (*DepositRequest_DeploymentWithEndpoints) Descriptor() ([]byte, []int) {
	return file_pb_bank_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DepositRequest_DeploymentWithEndpoints) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *DepositRequest_DeploymentWithEndpoints) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_pb_bank_proto protoreflect.FileDescriptor

const file_pb_bank_proto_rawDesc = "" +
	"\n" +
	"\rpb/bank.proto\x12\x02pb\"\xa7\x05\n" +
	"\x0eDepositRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12D\n" +
	"\bclusters\x18\x04 \x03(\v2(.pb.DepositRequest.ClusterWithNamespacesR\bclusters\x12`\n" +
	"\x17cluster_with_namespaces\x18\x05 \x01(\v2(.pb.DepositRequest.ClusterWithNamespacesR\x15clusterWithNamespaces\x1a\x8b\x01\n" +
	"\x15ClusterWithNamespaces\x12%\n" +
	"\acluster\x18\x01 \x01(\v2\v.pb.ClusterR\acluster\x12K\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\v2+.pb.DepositRequest.NamespaceWithDeploymentsR\n" +
	"namespaces\x1a\x95\x01\n" +
	"\x18NamespaceWithDeployments\x12+\n" +
	"\tnamespace\x18\x01 \x01(\v2\r.pb.NamespaceR\tnamespace\x12L\n" +
	"\vdeployments\x18\x02 \x03(\v2*.pb.DepositRequest.DeploymentWithEndpointsR\vdeployments\x1au\n" +
	"\x17DeploymentWithEndpoints\x12.\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x0e.pb.DeploymentR\n" +
	"deployment\x12*\n" +
	"\tendpoints\x18\x02 \x03(\v2\f.pb.EndpointR\tendpoints\"\f\n" +
	"\n" +
	"Deployment\"\n" +
	"\n" +
	"\bEndpoint\"\v\n" +
	"\tNamespace\"\t\n" +
	"\aCluster\"\x1e\n" +
	"\fDepositReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id27\n" +
	"\x04Bank\x12/\n" +
	"\aDeposit\x12\x12.pb.DepositRequest\x1a\x10.pb.DepositReplyB\x06Z\x04.;pbb\x06proto3"

var (
	file_pb_bank_proto_rawDescOnce sync.Once
	file_pb_bank_proto_rawDescData []byte
)

func file_pb_bank_proto_rawDescGZIP() []byte {
	file_pb_bank_proto_rawDescOnce.Do(func() {
		file_pb_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_bank_proto_rawDesc), len(file_pb_bank_proto_rawDesc)))
	})
	return file_pb_bank_proto_rawDescData
}

var file_pb_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_bank_proto_goTypes = []any{
	(*DepositRequest)(nil),                          // 0: pb.DepositRequest
	(*Deployment)(nil),                              // 1: pb.Deployment
	(*Endpoint)(nil),                                // 2: pb.Endpoint
	(*Namespace)(nil),                               // 3: pb.Namespace
	(*Cluster)(nil),                                 // 4: pb.Cluster
	(*DepositReply)(nil),                            // 5: pb.DepositReply
	(*DepositRequest_ClusterWithNamespaces)(nil),    // 6: pb.DepositRequest.ClusterWithNamespaces
	(*DepositRequest_NamespaceWithDeployments)(nil), // 7: pb.DepositRequest.NamespaceWithDeployments
	(*DepositRequest_DeploymentWithEndpoints)(nil),  // 8: pb.DepositRequest.DeploymentWithEndpoints
}
var file_pb_bank_proto_depIdxs = []int32{
	6, // 0: pb.DepositRequest.clusters:type_name -> pb.DepositRequest.ClusterWithNamespaces
	6, // 1: pb.DepositRequest.cluster_with_namespaces:type_name -> pb.DepositRequest.ClusterWithNamespaces
	4, // 2: pb.DepositRequest.ClusterWithNamespaces.cluster:type_name -> pb.Cluster
	7, // 3: pb.DepositRequest.ClusterWithNamespaces.namespaces:type_name -> pb.DepositRequest.NamespaceWithDeployments
	3, // 4: pb.DepositRequest.NamespaceWithDeployments.namespace:type_name -> pb.Namespace
	8, // 5: pb.DepositRequest.NamespaceWithDeployments.deployments:type_name -> pb.DepositRequest.DeploymentWithEndpoints
	1, // 6: pb.DepositRequest.DeploymentWithEndpoints.deployment:type_name -> pb.Deployment
	2, // 7: pb.DepositRequest.DeploymentWithEndpoints.endpoints:type_name -> pb.Endpoint
	0, // 8: pb.Bank.Deposit:input_type -> pb.DepositRequest
	5, // 9: pb.Bank.Deposit:output_type -> pb.DepositReply
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pb_bank_proto_init() }
func file_pb_bank_proto_init() {
	if File_pb_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_bank_proto_rawDesc), len(file_pb_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_bank_proto_goTypes,
		DependencyIndexes: file_pb_bank_proto_depIdxs,
		MessageInfos:      file_pb_bank_proto_msgTypes,
	}.Build()
	File_pb_bank_proto = out.File
	file_pb_bank_proto_goTypes = nil
	file_pb_bank_proto_depIdxs = nil
}
